// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package agentclient

import (
	"context"

	"github.com/wujunhui99/agents_im/service/agent/rpc/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentDefinition                    = agent.AgentDefinition
	AgentDefinitionResponse            = agent.AgentDefinitionResponse
	AgentEntity                        = agent.AgentEntity
	AgentFileReadAudit                 = agent.AgentFileReadAudit
	AgentPromptDefinition              = agent.AgentPromptDefinition
	AgentPythonExecAudit               = agent.AgentPythonExecAudit
	AgentResponse                      = agent.AgentResponse
	AgentRunAudit                      = agent.AgentRunAudit
	AgentToolCallAudit                 = agent.AgentToolCallAudit
	AgentToolDefinition                = agent.AgentToolDefinition
	ConversationAIHostingState         = agent.ConversationAIHostingState
	CountAgentRunsRequest              = agent.CountAgentRunsRequest
	CountAgentRunsResponse             = agent.CountAgentRunsResponse
	CreateAgentRequest                 = agent.CreateAgentRequest
	EnsureDefaultAssistantRequest      = agent.EnsureDefaultAssistantRequest
	EnsureDefaultAssistantResponse     = agent.EnsureDefaultAssistantResponse
	GetAgentDefinitionRequest          = agent.GetAgentDefinitionRequest
	GetAgentRequest                    = agent.GetAgentRequest
	GetAgentRunByTraceIDRequest        = agent.GetAgentRunByTraceIDRequest
	GetAgentRunRequest                 = agent.GetAgentRunRequest
	GetConversationAIHostingRequest    = agent.GetConversationAIHostingRequest
	ListAgentFileReadsResponse         = agent.ListAgentFileReadsResponse
	ListAgentPythonExecsResponse       = agent.ListAgentPythonExecsResponse
	ListAgentRunsRequest               = agent.ListAgentRunsRequest
	ListAgentRunsResponse              = agent.ListAgentRunsResponse
	ListAgentToolCallsResponse         = agent.ListAgentToolCallsResponse
	ListAgentsRequest                  = agent.ListAgentsRequest
	ListAgentsResponse                 = agent.ListAgentsResponse
	ListAuditByRunIDRequest            = agent.ListAuditByRunIDRequest
	UpdateAgentDefinitionRequest       = agent.UpdateAgentDefinitionRequest
	UpdateAgentRequest                 = agent.UpdateAgentRequest
	UpdateAgentStatusRequest           = agent.UpdateAgentStatusRequest
	UpdateConversationAIHostingRequest = agent.UpdateConversationAIHostingRequest

	Agent interface {
		// AI 托管开关：普通用户在双人单聊里开关「由 AI 代我回复」。
		GetConversationAIHosting(ctx context.Context, in *GetConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error)
		UpdateConversationAIHosting(ctx context.Context, in *UpdateConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error)
		// ---- agent CRUD（#606，agent-api BFF 经此面，不再 in-process logic / 直连 DB）----
		CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
		UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		// ---- agent 定义（系统提示词 + 工具绑定）----
		GetAgentDefinition(ctx context.Context, in *GetAgentDefinitionRequest, opts ...grpc.CallOption) (*AgentDefinitionResponse, error)
		UpdateAgentDefinition(ctx context.Context, in *UpdateAgentDefinitionRequest, opts ...grpc.CallOption) (*AgentDefinitionResponse, error)
		// EnsureDefaultAssistant 幂等装配默认助手的 agent 域部分（agent 行 + 提示词 + 工具绑定）。
		EnsureDefaultAssistant(ctx context.Context, in *EnsureDefaultAssistantRequest, opts ...grpc.CallOption) (*EnsureDefaultAssistantResponse, error)
		// ---- agent 审计只读面（#616：admin-rpc traces/dashboard 经此读，脱 internal/repository agent_audit）----
		ListAgentRuns(ctx context.Context, in *ListAgentRunsRequest, opts ...grpc.CallOption) (*ListAgentRunsResponse, error)
		CountAgentRuns(ctx context.Context, in *CountAgentRunsRequest, opts ...grpc.CallOption) (*CountAgentRunsResponse, error)
		GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*AgentRunAudit, error)
		GetAgentRunByTraceID(ctx context.Context, in *GetAgentRunByTraceIDRequest, opts ...grpc.CallOption) (*AgentRunAudit, error)
		ListAgentToolCallsByRunID(ctx context.Context, in *ListAuditByRunIDRequest, opts ...grpc.CallOption) (*ListAgentToolCallsResponse, error)
		ListAgentFileReadsByRunID(ctx context.Context, in *ListAuditByRunIDRequest, opts ...grpc.CallOption) (*ListAgentFileReadsResponse, error)
		ListAgentPythonExecsByRunID(ctx context.Context, in *ListAuditByRunIDRequest, opts ...grpc.CallOption) (*ListAgentPythonExecsResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

// AI 托管开关：普通用户在双人单聊里开关「由 AI 代我回复」。
func (m *defaultAgent) GetConversationAIHosting(ctx context.Context, in *GetConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetConversationAIHosting(ctx, in, opts...)
}

func (m *defaultAgent) UpdateConversationAIHosting(ctx context.Context, in *UpdateConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.UpdateConversationAIHosting(ctx, in, opts...)
}

// ---- agent CRUD（#606，agent-api BFF 经此面，不再 in-process logic / 直连 DB）----
func (m *defaultAgent) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.CreateAgent(ctx, in, opts...)
}

func (m *defaultAgent) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetAgent(ctx, in, opts...)
}

func (m *defaultAgent) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListAgents(ctx, in, opts...)
}

func (m *defaultAgent) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.UpdateAgent(ctx, in, opts...)
}

func (m *defaultAgent) UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.UpdateAgentStatus(ctx, in, opts...)
}

// ---- agent 定义（系统提示词 + 工具绑定）----
func (m *defaultAgent) GetAgentDefinition(ctx context.Context, in *GetAgentDefinitionRequest, opts ...grpc.CallOption) (*AgentDefinitionResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetAgentDefinition(ctx, in, opts...)
}

func (m *defaultAgent) UpdateAgentDefinition(ctx context.Context, in *UpdateAgentDefinitionRequest, opts ...grpc.CallOption) (*AgentDefinitionResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.UpdateAgentDefinition(ctx, in, opts...)
}

// EnsureDefaultAssistant 幂等装配默认助手的 agent 域部分（agent 行 + 提示词 + 工具绑定）。
func (m *defaultAgent) EnsureDefaultAssistant(ctx context.Context, in *EnsureDefaultAssistantRequest, opts ...grpc.CallOption) (*EnsureDefaultAssistantResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.EnsureDefaultAssistant(ctx, in, opts...)
}

// ---- agent 审计只读面（#616：admin-rpc traces/dashboard 经此读，脱 internal/repository agent_audit）----
func (m *defaultAgent) ListAgentRuns(ctx context.Context, in *ListAgentRunsRequest, opts ...grpc.CallOption) (*ListAgentRunsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListAgentRuns(ctx, in, opts...)
}

func (m *defaultAgent) CountAgentRuns(ctx context.Context, in *CountAgentRunsRequest, opts ...grpc.CallOption) (*CountAgentRunsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.CountAgentRuns(ctx, in, opts...)
}

func (m *defaultAgent) GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*AgentRunAudit, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetAgentRun(ctx, in, opts...)
}

func (m *defaultAgent) GetAgentRunByTraceID(ctx context.Context, in *GetAgentRunByTraceIDRequest, opts ...grpc.CallOption) (*AgentRunAudit, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetAgentRunByTraceID(ctx, in, opts...)
}

func (m *defaultAgent) ListAgentToolCallsByRunID(ctx context.Context, in *ListAuditByRunIDRequest, opts ...grpc.CallOption) (*ListAgentToolCallsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListAgentToolCallsByRunID(ctx, in, opts...)
}

func (m *defaultAgent) ListAgentFileReadsByRunID(ctx context.Context, in *ListAuditByRunIDRequest, opts ...grpc.CallOption) (*ListAgentFileReadsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListAgentFileReadsByRunID(ctx, in, opts...)
}

func (m *defaultAgent) ListAgentPythonExecsByRunID(ctx context.Context, in *ListAuditByRunIDRequest, opts ...grpc.CallOption) (*ListAgentPythonExecsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListAgentPythonExecsByRunID(ctx, in, opts...)
}
