// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddFriendData struct {
	Friendship Friendship `json:"friendship"`
	Created    bool       `json:"created"`
}

type AddFriendReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	UserID        string `json:"user_id"`
}

type AddFriendResp struct {
	Code    string        `json:"code"`
	Message string        `json:"message"`
	Data    AddFriendData `json:"data"`
}

type AddMemberReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	GroupID       string `path:"group_id"`
	UserID        string `json:"user_id,optional"`
}

type AuthData struct {
	UserID     string `json:"user_id"`
	Identifier string `json:"identifier"`
	Token      string `json:"token"`
	ExpiresAt  string `json:"expires_at"`
}

type AuthResp struct {
	Code    string   `json:"code"`
	Message string   `json:"message"`
	Data    AuthData `json:"data"`
}

type ConversationSeqState struct {
	ConversationID string   `json:"conversationId"`
	MaxSeq         int64    `json:"maxSeq"`
	HasReadSeq     int64    `json:"hasReadSeq"`
	UnreadCount    int64    `json:"unreadCount"`
	MaxSeqTime     int64    `json:"maxSeqTime"`
	LastMessage    *Message `json:"lastMessage,omitempty"`
}

type ConversationSeqsData struct {
	States []ConversationSeqState `json:"states"`
}

type ConversationSeqsReq struct {
	CurrentUserID   string `header:"X-User-Id,optional"`
	ConversationIDs string `form:"conversationIds,optional"`
}

type ConversationSeqsResp struct {
	Code    string               `json:"code"`
	Message string               `json:"message"`
	Data    ConversationSeqsData `json:"data"`
}

type CreateGroupReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	Name          string `json:"name"`
	Description   string `json:"description,optional"`
}

type CreateUserReq struct {
	Identifier  string `json:"identifier"`
	DisplayName string `json:"display_name,optional"`
	Name        string `json:"name,optional"`
	Gender      string `json:"gender,optional"`
	Age         int32  `json:"age,optional"`
	Region      string `json:"region,optional"`
}

type DeleteFriendData struct {
	Friendship Friendship `json:"friendship"`
	Deleted    bool       `json:"deleted"`
}

type DeleteFriendResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    DeleteFriendData `json:"data"`
}

type ExistsData struct {
	Identifier string `json:"identifier"`
	Exists     bool   `json:"exists"`
}

type ExistsReq struct {
	Identifier string `form:"identifier"`
}

type ExistsResp struct {
	Code    string     `json:"code"`
	Message string     `json:"message"`
	Data    ExistsData `json:"data"`
}

type FriendPathReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	UserID        string `path:"user_id"`
}

type Friendship struct {
	UserID    string `json:"user_id"`
	FriendID  string `json:"friend_id"`
	Status    string `json:"status"`
	IsFriend  bool   `json:"is_friend"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type FriendshipData struct {
	Friendship Friendship `json:"friendship"`
}

type FriendshipResp struct {
	Code    string         `json:"code"`
	Message string         `json:"message"`
	Data    FriendshipData `json:"data"`
}

type GetGroupReq struct {
	GroupID string `path:"group_id"`
}

type GetMeReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
}

type GetUserByIdentifierReq struct {
	Identifier string `path:"identifier"`
}

type Group struct {
	GroupID       string `json:"group_id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	CreatorUserID string `json:"creator_user_id"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type GroupMember struct {
	GroupID  string `json:"group_id"`
	UserID   string `json:"user_id"`
	State    string `json:"state"`
	JoinedAt string `json:"joined_at"`
	LeftAt   string `json:"left_at"`
}

type GroupResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    Group  `json:"data"`
}

type LeaveGroupReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	GroupID       string `path:"group_id"`
}

type ListFriendsData struct {
	Friends []Friendship `json:"friends"`
}

type ListFriendsReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
}

type ListFriendsResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    ListFriendsData `json:"data"`
}

type ListMembersData struct {
	GroupID string        `json:"group_id"`
	Members []GroupMember `json:"members"`
}

type ListMembersReq struct {
	GroupID string `path:"group_id"`
}

type ListMembersResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    ListMembersData `json:"data"`
}

type LoginReq struct {
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
}

type MarkConversationAsReadData struct {
	ConversationID string `json:"conversationId"`
	HasReadSeq     int64  `json:"hasReadSeq"`
	MaxSeq         int64  `json:"maxSeq"`
	UnreadCount    int64  `json:"unreadCount"`
	Updated        bool   `json:"updated"`
}

type MarkConversationAsReadReq struct {
	CurrentUserID  string `header:"X-User-Id,optional"`
	ConversationID string `path:"conversation_id"`
	HasReadSeq     int64  `json:"hasReadSeq"`
}

type MarkConversationAsReadResp struct {
	Code    string                     `json:"code"`
	Message string                     `json:"message"`
	Data    MarkConversationAsReadData `json:"data"`
}

type MemberData struct {
	Member        GroupMember `json:"member"`
	AlreadyMember bool        `json:"already_member"`
}

type MemberResp struct {
	Code    string     `json:"code"`
	Message string     `json:"message"`
	Data    MemberData `json:"data"`
}

type Message struct {
	ServerMsgID    string `json:"serverMsgId"`
	ClientMsgID    string `json:"clientMsgId"`
	ConversationID string `json:"conversationId"`
	Seq            int64  `json:"seq"`
	SenderID       string `json:"senderId"`
	ReceiverID     string `json:"receiverId"`
	GroupID        string `json:"groupId"`
	ChatType       string `json:"chatType"`
	ContentType    string `json:"contentType"`
	Content        string `json:"content"`
	SendTime       int64  `json:"sendTime"`
	CreatedAt      int64  `json:"createdAt"`
}

type PullMessagesData struct {
	Messages []Message `json:"messages"`
	IsEnd    bool      `json:"isEnd"`
	NextSeq  int64     `json:"nextSeq"`
}

type PullMessagesReq struct {
	CurrentUserID  string `header:"X-User-Id,optional"`
	ConversationID string `path:"conversation_id"`
	FromSeq        int64  `form:"fromSeq,optional"`
	ToSeq          int64  `form:"toSeq,optional"`
	Limit          int64  `form:"limit,optional"`
	Order          string `form:"order,optional"`
}

type PullMessagesResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    PullMessagesData `json:"data"`
}

type RegisterReq struct {
	Identifier  string `json:"identifier"`
	Password    string `json:"password"`
	DisplayName string `json:"display_name,optional"`
	Name        string `json:"name,optional"`
	Gender      string `json:"gender,optional"`
	Age         int32  `json:"age,optional"`
	Region      string `json:"region,optional"`
}

type SendMessageData struct {
	Message      Message `json:"message"`
	Deduplicated bool    `json:"deduplicated"`
}

type SendMessageReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	ReceiverID    string `json:"receiverId,optional"`
	GroupID       string `json:"groupId,optional"`
	ChatType      string `json:"chatType"`
	ClientMsgID   string `json:"clientMsgId"`
	ContentType   string `json:"contentType"`
	Content       string `json:"content"`
}

type SendMessageResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    SendMessageData `json:"data"`
}

type UpdateMeReq struct {
	CurrentUserID string `header:"X-User-Id,optional"`
	UserID        string `json:"user_id,optional"`
	Identifier    string `json:"identifier,optional"`
	DisplayName   string `json:"display_name,optional"`
	Name          string `json:"name,optional"`
	Gender        string `json:"gender,optional"`
	Age           int32  `json:"age,optional"`
	Region        string `json:"region,optional"`
}

type User struct {
	UserID      string `json:"user_id"`
	Identifier  string `json:"identifier"`
	DisplayName string `json:"display_name"`
	Name        string `json:"name"`
	Gender      string `json:"gender"`
	Age         int32  `json:"age"`
	Region      string `json:"region"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type UserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    User   `json:"data"`
}

type ValidateTokenData struct {
	Valid      bool   `json:"valid"`
	UserID     string `json:"user_id"`
	Identifier string `json:"identifier"`
	ExpiresAt  string `json:"expires_at"`
}

type ValidateTokenReq struct {
	Token string `json:"token"`
}

type ValidateTokenResp struct {
	Code    string            `json:"code"`
	Message string            `json:"message"`
	Data    ValidateTokenData `json:"data"`
}
