// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: mail.proto

package mailclient

import (
	"context"

	"github.com/wujunhui99/agents_im/service/third/rpc/mail"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendTemplateEmailRequest  = mail.SendTemplateEmailRequest
	SendTemplateEmailResponse = mail.SendTemplateEmailResponse

	Mail interface {
		SendTemplateEmail(ctx context.Context, in *SendTemplateEmailRequest, opts ...grpc.CallOption) (*SendTemplateEmailResponse, error)
	}

	defaultMail struct {
		cli zrpc.Client
	}
)

func NewMail(cli zrpc.Client) Mail {
	return &defaultMail{
		cli: cli,
	}
}

func (m *defaultMail) SendTemplateEmail(ctx context.Context, in *SendTemplateEmailRequest, opts ...grpc.CallOption) (*SendTemplateEmailResponse, error) {
	client := mail.NewMailClient(m.cli.Conn())
	return client.SendTemplateEmail(ctx, in, opts...)
}
