// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{}, true)
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupsFieldNames, "group_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, groupId string) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, groupId string) error
	}

	defaultGroupsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groups struct {
		GroupId          string    `db:"group_id"`
		Name             string    `db:"name"`
		Description      string    `db:"description"`
		CreatorAccountId string    `db:"creator_account_id"`
		CreatedAt        time.Time `db:"created_at"`
		UpdatedAt        time.Time `db:"updated_at"`
	}
)

func newGroupsModel(conn sqlx.SqlConn) *defaultGroupsModel {
	return &defaultGroupsModel{
		conn:  conn,
		table: `"public"."groups"`,
	}
}

func (m *defaultGroupsModel) Delete(ctx context.Context, groupId string) error {
	query := fmt.Sprintf("delete from %s where group_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, groupId)
	return err
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, groupId string) (*Groups, error) {
	query := fmt.Sprintf("select %s from %s where group_id = $1 limit 1", groupsRows, m.table)
	var resp Groups
	err := m.conn.QueryRowCtx(ctx, &resp, query, groupId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, groupsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GroupId, data.Name, data.Description, data.CreatorAccountId)
	return ret, err
}

func (m *defaultGroupsModel) Update(ctx context.Context, data *Groups) error {
	query := fmt.Sprintf("update %s set %s where group_id = $1", m.table, groupsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.GroupId, data.Name, data.Description, data.CreatorAccountId)
	return err
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
