// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupMembersFieldNames          = builder.RawFieldNames(&GroupMembers{}, true)
	groupMembersRows                = strings.Join(groupMembersFieldNames, ",")
	groupMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(groupMembersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupMembersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupMembersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	groupMembersModel interface {
		Insert(ctx context.Context, data *GroupMembers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GroupMembers, error)
		FindOneByGroupIdAccountId(ctx context.Context, groupId string, accountId string) (*GroupMembers, error)
		Update(ctx context.Context, data *GroupMembers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GroupMembers struct {
		GroupId   string       `db:"group_id"`
		AccountId string       `db:"account_id"`
		Role      int64        `db:"role"`
		Status    int64        `db:"status"`
		JoinTime  time.Time    `db:"join_time"`
		LeftAt    sql.NullTime `db:"left_at"`
		CreatedAt time.Time    `db:"created_at"`
		UpdatedAt time.Time    `db:"updated_at"`
		Id        int64        `db:"id"`
	}
)

func newGroupMembersModel(conn sqlx.SqlConn) *defaultGroupMembersModel {
	return &defaultGroupMembersModel{
		conn:  conn,
		table: `"public"."group_members"`,
	}
}

func (m *defaultGroupMembersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupMembersModel) FindOne(ctx context.Context, id int64) (*GroupMembers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupMembersRows, m.table)
	var resp GroupMembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMembersModel) FindOneByGroupIdAccountId(ctx context.Context, groupId string, accountId string) (*GroupMembers, error) {
	var resp GroupMembers
	query := fmt.Sprintf("select %s from %s where group_id = $1 and account_id = $2 limit 1", groupMembersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, groupId, accountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMembersModel) Insert(ctx context.Context, data *GroupMembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, groupMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GroupId, data.AccountId, data.Role, data.Status, data.JoinTime, data.LeftAt)
	return ret, err
}

func (m *defaultGroupMembersModel) Update(ctx context.Context, newData *GroupMembers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, groupMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.GroupId, newData.AccountId, newData.Role, newData.Status, newData.JoinTime, newData.LeftAt)
	return err
}

func (m *defaultGroupMembersModel) tableName() string {
	return m.table
}
