// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userclient

import (
	"context"

	"github.com/wujunhui99/agents_im/service/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTestAccountRequest   = user.CreateTestAccountRequest
	CreateTestAccountResponse  = user.CreateTestAccountResponse
	CountAccountsRequest       = user.CountAccountsRequest
	CountAccountsResponse      = user.CountAccountsResponse
	CreateUserRequest          = user.CreateUserRequest
	ExistsByIdentifierRequest  = user.ExistsByIdentifierRequest
	ExistsByIdentifierResponse = user.ExistsByIdentifierResponse
	GetUserByIDRequest         = user.GetUserByIDRequest
	GetUserByIdentifierRequest = user.GetUserByIdentifierRequest
	GetUsersByIDsRequest       = user.GetUsersByIDsRequest
	GetUsersByIDsResponse      = user.GetUsersByIDsResponse
	SearchAccountsRequest      = user.SearchAccountsRequest
	SearchAccountsResponse     = user.SearchAccountsResponse
	UpdateUserAvatarRequest    = user.UpdateUserAvatarRequest
	UpdateUserProfileRequest   = user.UpdateUserProfileRequest
	UserEntity                 = user.UserEntity
	UserResponse               = user.UserResponse

	User interface {
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
		GetUserByIdentifier(ctx context.Context, in *GetUserByIdentifierRequest, opts ...grpc.CallOption) (*UserResponse, error)
		ExistsByIdentifier(ctx context.Context, in *ExistsByIdentifierRequest, opts ...grpc.CallOption) (*ExistsByIdentifierResponse, error)
		GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*UserResponse, error)
		GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*GetUsersByIDsResponse, error)
		// SearchAccounts 按 query 模糊搜账号（管理后台跨域只读，经属主 user-rpc）。
		SearchAccounts(ctx context.Context, in *SearchAccountsRequest, opts ...grpc.CallOption) (*SearchAccountsResponse, error)
		// CountAccounts 统计账号总数（管理后台 dashboard 用）。
		CountAccounts(ctx context.Context, in *CountAccountsRequest, opts ...grpc.CallOption) (*CountAccountsResponse, error)
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UserResponse, error)
		UpdateUserAvatar(ctx context.Context, in *UpdateUserAvatarRequest, opts ...grpc.CallOption) (*UserResponse, error)
		// CreateTestAccount 创建管理后台用的测试账户（account_type=test，不绑定邮箱）。
		CreateTestAccount(ctx context.Context, in *CreateTestAccountRequest, opts ...grpc.CallOption) (*CreateTestAccountResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUser) GetUserByIdentifier(ctx context.Context, in *GetUserByIdentifierRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserByIdentifier(ctx, in, opts...)
}

func (m *defaultUser) ExistsByIdentifier(ctx context.Context, in *ExistsByIdentifierRequest, opts ...grpc.CallOption) (*ExistsByIdentifierResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ExistsByIdentifier(ctx, in, opts...)
}

func (m *defaultUser) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserByID(ctx, in, opts...)
}

func (m *defaultUser) GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*GetUsersByIDsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUsersByIDs(ctx, in, opts...)
}

func (m *defaultUser) SearchAccounts(ctx context.Context, in *SearchAccountsRequest, opts ...grpc.CallOption) (*SearchAccountsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SearchAccounts(ctx, in, opts...)
}

func (m *defaultUser) CountAccounts(ctx context.Context, in *CountAccountsRequest, opts ...grpc.CallOption) (*CountAccountsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CountAccounts(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserAvatar(ctx context.Context, in *UpdateUserAvatarRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserAvatar(ctx, in, opts...)
}

// CreateTestAccount 创建管理后台用的测试账户（account_type=test，不绑定邮箱）。
func (m *defaultUser) CreateTestAccount(ctx context.Context, in *CreateTestAccountRequest, opts ...grpc.CallOption) (*CreateTestAccountResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateTestAccount(ctx, in, opts...)
}
