// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: friends.proto

package server

import (
	"context"

	friends "github.com/wujunhui99/agents_im/service/friends/rpc/friends"
	"github.com/wujunhui99/agents_im/service/friends/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/friends/rpc/internal/svc"
)

type FriendsServer struct {
	svcCtx *svc.ServiceContext
	friends.UnimplementedFriendsServer
}

func NewFriendsServer(svcCtx *svc.ServiceContext) *FriendsServer {
	return &FriendsServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendsServer) AddFriend(ctx context.Context, in *friends.AddFriendRequest) (*friends.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *FriendsServer) DeleteFriend(ctx context.Context, in *friends.DeleteFriendRequest) (*friends.DeleteFriendResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *FriendsServer) ListFriends(ctx context.Context, in *friends.ListFriendsRequest) (*friends.ListFriendsResponse, error) {
	l := logic.NewListFriendsLogic(ctx, s.svcCtx)
	return l.ListFriends(in)
}

func (s *FriendsServer) GetFriendship(ctx context.Context, in *friends.GetFriendshipRequest) (*friends.GetFriendshipResponse, error) {
	l := logic.NewGetFriendshipLogic(ctx, s.svcCtx)
	return l.GetFriendship(in)
}

func (s *FriendsServer) ListFriendRequests(ctx context.Context, in *friends.ListFriendRequestsRequest) (*friends.ListFriendRequestsResponse, error) {
	l := logic.NewListFriendRequestsLogic(ctx, s.svcCtx)
	return l.ListFriendRequests(in)
}

func (s *FriendsServer) AcceptFriendRequest(ctx context.Context, in *friends.FriendRequestDecisionRequest) (*friends.FriendRequestDecisionResponse, error) {
	l := logic.NewAcceptFriendRequestLogic(ctx, s.svcCtx)
	return l.AcceptFriendRequest(in)
}

func (s *FriendsServer) RejectFriendRequest(ctx context.Context, in *friends.FriendRequestDecisionRequest) (*friends.FriendRequestDecisionResponse, error) {
	l := logic.NewRejectFriendRequestLogic(ctx, s.svcCtx)
	return l.RejectFriendRequest(in)
}

func (s *FriendsServer) EnsureFriendship(ctx context.Context, in *friends.EnsureFriendshipRequest) (*friends.EnsureFriendshipResponse, error) {
	l := logic.NewEnsureFriendshipLogic(ctx, s.svcCtx)
	return l.EnsureFriendship(in)
}
