// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: service/message/rpc/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId           string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	ClientMsgId           string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ConversationId        string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq                   int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderId              string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId            string                 `protobuf:"bytes,6,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	GroupId               string                 `protobuf:"bytes,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatType              string                 `protobuf:"bytes,8,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	ContentType           string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content               string                 `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	MessageOrigin         string                 `protobuf:"bytes,11,opt,name=message_origin,json=messageOrigin,proto3" json:"message_origin,omitempty"`
	AgentAccountId        string                 `protobuf:"bytes,12,opt,name=agent_account_id,json=agentAccountId,proto3" json:"agent_account_id,omitempty"`
	TriggerServerMsgId    string                 `protobuf:"bytes,13,opt,name=trigger_server_msg_id,json=triggerServerMsgId,proto3" json:"trigger_server_msg_id,omitempty"`
	AgentRunId            string                 `protobuf:"bytes,14,opt,name=agent_run_id,json=agentRunId,proto3" json:"agent_run_id,omitempty"`
	AllowRecursiveTrigger bool                   `protobuf:"varint,15,opt,name=allow_recursive_trigger,json=allowRecursiveTrigger,proto3" json:"allow_recursive_trigger,omitempty"`
	SendTime              int64                  `protobuf:"varint,16,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_service_message_rpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *Message) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Message) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Message) GetChatType() string {
	if x != nil {
		return x.ChatType
	}
	return ""
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMessageOrigin() string {
	if x != nil {
		return x.MessageOrigin
	}
	return ""
}

func (x *Message) GetAgentAccountId() string {
	if x != nil {
		return x.AgentAccountId
	}
	return ""
}

func (x *Message) GetTriggerServerMsgId() string {
	if x != nil {
		return x.TriggerServerMsgId
	}
	return ""
}

func (x *Message) GetAgentRunId() string {
	if x != nil {
		return x.AgentRunId
	}
	return ""
}

func (x *Message) GetAllowRecursiveTrigger() bool {
	if x != nil {
		return x.AllowRecursiveTrigger
	}
	return false
}

func (x *Message) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ConversationSeqState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MaxSeq         int64                  `protobuf:"varint,2,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	HasReadSeq     int64                  `protobuf:"varint,3,opt,name=has_read_seq,json=hasReadSeq,proto3" json:"has_read_seq,omitempty"`
	UnreadCount    int64                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	MaxSeqTime     int64                  `protobuf:"varint,5,opt,name=max_seq_time,json=maxSeqTime,proto3" json:"max_seq_time,omitempty"`
	LastMessage    *Message               `protobuf:"bytes,6,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationSeqState) Reset() {
	*x = ConversationSeqState{}
	mi := &file_service_message_rpc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSeqState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSeqState) ProtoMessage() {}

func (x *ConversationSeqState) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSeqState.ProtoReflect.Descriptor instead.
func (*ConversationSeqState) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationSeqState) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationSeqState) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *ConversationSeqState) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *ConversationSeqState) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationSeqState) GetMaxSeqTime() int64 {
	if x != nil {
		return x.MaxSeqTime
	}
	return 0
}

func (x *ConversationSeqState) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type SendMessageRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SenderId              string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId            string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	GroupId               string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatType              string                 `protobuf:"bytes,4,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	ClientMsgId           string                 `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ContentType           string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content               string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	MessageOrigin         string                 `protobuf:"bytes,8,opt,name=message_origin,json=messageOrigin,proto3" json:"message_origin,omitempty"`
	AgentAccountId        string                 `protobuf:"bytes,9,opt,name=agent_account_id,json=agentAccountId,proto3" json:"agent_account_id,omitempty"`
	TriggerServerMsgId    string                 `protobuf:"bytes,10,opt,name=trigger_server_msg_id,json=triggerServerMsgId,proto3" json:"trigger_server_msg_id,omitempty"`
	AgentRunId            string                 `protobuf:"bytes,11,opt,name=agent_run_id,json=agentRunId,proto3" json:"agent_run_id,omitempty"`
	AllowRecursiveTrigger bool                   `protobuf:"varint,12,opt,name=allow_recursive_trigger,json=allowRecursiveTrigger,proto3" json:"allow_recursive_trigger,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_service_message_rpc_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendMessageRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SendMessageRequest) GetChatType() string {
	if x != nil {
		return x.ChatType
	}
	return ""
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetMessageOrigin() string {
	if x != nil {
		return x.MessageOrigin
	}
	return ""
}

func (x *SendMessageRequest) GetAgentAccountId() string {
	if x != nil {
		return x.AgentAccountId
	}
	return ""
}

func (x *SendMessageRequest) GetTriggerServerMsgId() string {
	if x != nil {
		return x.TriggerServerMsgId
	}
	return ""
}

func (x *SendMessageRequest) GetAgentRunId() string {
	if x != nil {
		return x.AgentRunId
	}
	return ""
}

func (x *SendMessageRequest) GetAllowRecursiveTrigger() bool {
	if x != nil {
		return x.AllowRecursiveTrigger
	}
	return false
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_service_message_rpc_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type PullMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FromSeq        int64                  `protobuf:"varint,3,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	ToSeq          int64                  `protobuf:"varint,4,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Order          string                 `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullMessagesRequest) Reset() {
	*x = PullMessagesRequest{}
	mi := &file_service_message_rpc_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest) ProtoMessage() {}

func (x *PullMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{4}
}

func (x *PullMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PullMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PullMessagesRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *PullMessagesRequest) GetToSeq() int64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

func (x *PullMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PullMessagesRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type PullMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	IsEnd         bool                   `protobuf:"varint,2,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	NextSeq       int64                  `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse) Reset() {
	*x = PullMessagesResponse{}
	mi := &file_service_message_rpc_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse) ProtoMessage() {}

func (x *PullMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{5}
}

func (x *PullMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PullMessagesResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *PullMessagesResponse) GetNextSeq() int64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

type GetConversationSeqsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationIds []string               `protobuf:"bytes,2,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConversationSeqsRequest) Reset() {
	*x = GetConversationSeqsRequest{}
	mi := &file_service_message_rpc_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationSeqsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationSeqsRequest) ProtoMessage() {}

func (x *GetConversationSeqsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationSeqsRequest.ProtoReflect.Descriptor instead.
func (*GetConversationSeqsRequest) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationSeqsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConversationSeqsRequest) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type GetConversationSeqsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	States        []*ConversationSeqState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationSeqsResponse) Reset() {
	*x = GetConversationSeqsResponse{}
	mi := &file_service_message_rpc_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationSeqsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationSeqsResponse) ProtoMessage() {}

func (x *GetConversationSeqsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationSeqsResponse.ProtoReflect.Descriptor instead.
func (*GetConversationSeqsResponse) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetConversationSeqsResponse) GetStates() []*ConversationSeqState {
	if x != nil {
		return x.States
	}
	return nil
}

type MarkConversationAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	HasReadSeq     int64                  `protobuf:"varint,3,opt,name=has_read_seq,json=hasReadSeq,proto3" json:"has_read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkConversationAsReadRequest) Reset() {
	*x = MarkConversationAsReadRequest{}
	mi := &file_service_message_rpc_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConversationAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConversationAsReadRequest) ProtoMessage() {}

func (x *MarkConversationAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConversationAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkConversationAsReadRequest) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{8}
}

func (x *MarkConversationAsReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkConversationAsReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MarkConversationAsReadRequest) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

type MarkConversationAsReadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	HasReadSeq     int64                  `protobuf:"varint,2,opt,name=has_read_seq,json=hasReadSeq,proto3" json:"has_read_seq,omitempty"`
	MaxSeq         int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	UnreadCount    int64                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Updated        bool                   `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkConversationAsReadResponse) Reset() {
	*x = MarkConversationAsReadResponse{}
	mi := &file_service_message_rpc_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConversationAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConversationAsReadResponse) ProtoMessage() {}

func (x *MarkConversationAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_rpc_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConversationAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkConversationAsReadResponse) Descriptor() ([]byte, []int) {
	return file_service_message_rpc_message_proto_rawDescGZIP(), []int{9}
}

func (x *MarkConversationAsReadResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MarkConversationAsReadResponse) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *MarkConversationAsReadResponse) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *MarkConversationAsReadResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *MarkConversationAsReadResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_service_message_rpc_message_proto protoreflect.FileDescriptor

const file_service_message_rpc_message_proto_rawDesc = "" +
	"\n" +
	"!service/message/rpc/message.proto\x12\amessage\"\xd9\x04\n" +
	"\aMessage\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x06 \x01(\tR\n" +
	"receiverId\x12\x19\n" +
	"\bgroup_id\x18\a \x01(\tR\agroupId\x12\x1b\n" +
	"\tchat_type\x18\b \x01(\tR\bchatType\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12%\n" +
	"\x0emessage_origin\x18\v \x01(\tR\rmessageOrigin\x12(\n" +
	"\x10agent_account_id\x18\f \x01(\tR\x0eagentAccountId\x121\n" +
	"\x15trigger_server_msg_id\x18\r \x01(\tR\x12triggerServerMsgId\x12 \n" +
	"\fagent_run_id\x18\x0e \x01(\tR\n" +
	"agentRunId\x126\n" +
	"\x17allow_recursive_trigger\x18\x0f \x01(\bR\x15allowRecursiveTrigger\x12\x1b\n" +
	"\tsend_time\x18\x10 \x01(\x03R\bsendTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\x03R\tcreatedAt\"\xf4\x01\n" +
	"\x14ConversationSeqState\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\amax_seq\x18\x02 \x01(\x03R\x06maxSeq\x12 \n" +
	"\fhas_read_seq\x18\x03 \x01(\x03R\n" +
	"hasReadSeq\x12!\n" +
	"\funread_count\x18\x04 \x01(\x03R\vunreadCount\x12 \n" +
	"\fmax_seq_time\x18\x05 \x01(\x03R\n" +
	"maxSeqTime\x123\n" +
	"\flast_message\x18\x06 \x01(\v2\x10.message.MessageR\vlastMessage\"\xc9\x03\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x1b\n" +
	"\tchat_type\x18\x04 \x01(\tR\bchatType\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\tR\vclientMsgId\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12%\n" +
	"\x0emessage_origin\x18\b \x01(\tR\rmessageOrigin\x12(\n" +
	"\x10agent_account_id\x18\t \x01(\tR\x0eagentAccountId\x121\n" +
	"\x15trigger_server_msg_id\x18\n" +
	" \x01(\tR\x12triggerServerMsgId\x12 \n" +
	"\fagent_run_id\x18\v \x01(\tR\n" +
	"agentRunId\x126\n" +
	"\x17allow_recursive_trigger\x18\f \x01(\bR\x15allowRecursiveTrigger\"e\n" +
	"\x13SendMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.message.MessageR\amessage\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"\xb5\x01\n" +
	"\x13PullMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bfrom_seq\x18\x03 \x01(\x03R\afromSeq\x12\x15\n" +
	"\x06to_seq\x18\x04 \x01(\x03R\x05toSeq\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05order\x18\x06 \x01(\tR\x05order\"v\n" +
	"\x14PullMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\x12\x15\n" +
	"\x06is_end\x18\x02 \x01(\bR\x05isEnd\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x03R\anextSeq\"`\n" +
	"\x1aGetConversationSeqsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10conversation_ids\x18\x02 \x03(\tR\x0fconversationIds\"T\n" +
	"\x1bGetConversationSeqsResponse\x125\n" +
	"\x06states\x18\x01 \x03(\v2\x1d.message.ConversationSeqStateR\x06states\"\x83\x01\n" +
	"\x1dMarkConversationAsReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12 \n" +
	"\fhas_read_seq\x18\x03 \x01(\x03R\n" +
	"hasReadSeq\"\xc1\x01\n" +
	"\x1eMarkConversationAsReadResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12 \n" +
	"\fhas_read_seq\x18\x02 \x01(\x03R\n" +
	"hasReadSeq\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\x12!\n" +
	"\funread_count\x18\x04 \x01(\x03R\vunreadCount\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\bR\aupdated2\xf4\x02\n" +
	"\x0eMessageService\x12H\n" +
	"\vSendMessage\x12\x1b.message.SendMessageRequest\x1a\x1c.message.SendMessageResponse\x12K\n" +
	"\fPullMessages\x12\x1c.message.PullMessagesRequest\x1a\x1d.message.PullMessagesResponse\x12`\n" +
	"\x13GetConversationSeqs\x12#.message.GetConversationSeqsRequest\x1a$.message.GetConversationSeqsResponse\x12i\n" +
	"\x16MarkConversationAsRead\x12&.message.MarkConversationAsReadRequest\x1a'.message.MarkConversationAsReadResponseB=Z;github.com/wujunhui99/agents_im/service/message/rpc/messageb\x06proto3"

var (
	file_service_message_rpc_message_proto_rawDescOnce sync.Once
	file_service_message_rpc_message_proto_rawDescData []byte
)

func file_service_message_rpc_message_proto_rawDescGZIP() []byte {
	file_service_message_rpc_message_proto_rawDescOnce.Do(func() {
		file_service_message_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_message_rpc_message_proto_rawDesc), len(file_service_message_rpc_message_proto_rawDesc)))
	})
	return file_service_message_rpc_message_proto_rawDescData
}

var file_service_message_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_message_rpc_message_proto_goTypes = []any{
	(*Message)(nil),                        // 0: message.Message
	(*ConversationSeqState)(nil),           // 1: message.ConversationSeqState
	(*SendMessageRequest)(nil),             // 2: message.SendMessageRequest
	(*SendMessageResponse)(nil),            // 3: message.SendMessageResponse
	(*PullMessagesRequest)(nil),            // 4: message.PullMessagesRequest
	(*PullMessagesResponse)(nil),           // 5: message.PullMessagesResponse
	(*GetConversationSeqsRequest)(nil),     // 6: message.GetConversationSeqsRequest
	(*GetConversationSeqsResponse)(nil),    // 7: message.GetConversationSeqsResponse
	(*MarkConversationAsReadRequest)(nil),  // 8: message.MarkConversationAsReadRequest
	(*MarkConversationAsReadResponse)(nil), // 9: message.MarkConversationAsReadResponse
}
var file_service_message_rpc_message_proto_depIdxs = []int32{
	0, // 0: message.ConversationSeqState.last_message:type_name -> message.Message
	0, // 1: message.SendMessageResponse.message:type_name -> message.Message
	0, // 2: message.PullMessagesResponse.messages:type_name -> message.Message
	1, // 3: message.GetConversationSeqsResponse.states:type_name -> message.ConversationSeqState
	2, // 4: message.MessageService.SendMessage:input_type -> message.SendMessageRequest
	4, // 5: message.MessageService.PullMessages:input_type -> message.PullMessagesRequest
	6, // 6: message.MessageService.GetConversationSeqs:input_type -> message.GetConversationSeqsRequest
	8, // 7: message.MessageService.MarkConversationAsRead:input_type -> message.MarkConversationAsReadRequest
	3, // 8: message.MessageService.SendMessage:output_type -> message.SendMessageResponse
	5, // 9: message.MessageService.PullMessages:output_type -> message.PullMessagesResponse
	7, // 10: message.MessageService.GetConversationSeqs:output_type -> message.GetConversationSeqsResponse
	9, // 11: message.MessageService.MarkConversationAsRead:output_type -> message.MarkConversationAsReadResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_message_rpc_message_proto_init() }
func file_service_message_rpc_message_proto_init() {
	if File_service_message_rpc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_message_rpc_message_proto_rawDesc), len(file_service_message_rpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_message_rpc_message_proto_goTypes,
		DependencyIndexes: file_service_message_rpc_message_proto_depIdxs,
		MessageInfos:      file_service_message_rpc_message_proto_msgTypes,
	}.Build()
	File_service_message_rpc_message_proto = out.File
	file_service_message_rpc_message_proto_goTypes = nil
	file_service_message_rpc_message_proto_depIdxs = nil
}
