// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: media.proto

package mediaclient

import (
	"context"

	"github.com/wujunhui99/agents_im/service/media/rpc/media"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CompleteUploadRequest       = media.CompleteUploadRequest
	CompleteUploadResponse      = media.CompleteUploadResponse
	CreateUploadIntentRequest   = media.CreateUploadIntentRequest
	CreateUploadIntentResponse  = media.CreateUploadIntentResponse
	GetAvatarDisplayURLRequest  = media.GetAvatarDisplayURLRequest
	GetDownloadURLRequest       = media.GetDownloadURLRequest
	GetDownloadURLResponse      = media.GetDownloadURLResponse
	GetMediaRequest             = media.GetMediaRequest
	MediaObject                 = media.MediaObject
	ValidateAvatarMediaRequest  = media.ValidateAvatarMediaRequest
	ValidateMessageMediaRequest = media.ValidateMessageMediaRequest
	ValidateMediaResponse       = media.ValidateMediaResponse

	Media interface {
		CreateUploadIntent(ctx context.Context, in *CreateUploadIntentRequest, opts ...grpc.CallOption) (*CreateUploadIntentResponse, error)
		CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
		GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*MediaObject, error)
		GetDownloadURL(ctx context.Context, in *GetDownloadURLRequest, opts ...grpc.CallOption) (*GetDownloadURLResponse, error)
		GetAvatarDisplayURL(ctx context.Context, in *GetAvatarDisplayURLRequest, opts ...grpc.CallOption) (*GetDownloadURLResponse, error)
		ValidateAvatarMedia(ctx context.Context, in *ValidateAvatarMediaRequest, opts ...grpc.CallOption) (*ValidateMediaResponse, error)
		ValidateMessageMedia(ctx context.Context, in *ValidateMessageMediaRequest, opts ...grpc.CallOption) (*ValidateMediaResponse, error)
	}

	defaultMedia struct {
		cli zrpc.Client
	}
)

func NewMedia(cli zrpc.Client) Media {
	return &defaultMedia{
		cli: cli,
	}
}

func (m *defaultMedia) CreateUploadIntent(ctx context.Context, in *CreateUploadIntentRequest, opts ...grpc.CallOption) (*CreateUploadIntentResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.CreateUploadIntent(ctx, in, opts...)
}

func (m *defaultMedia) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.CompleteUpload(ctx, in, opts...)
}

func (m *defaultMedia) GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*MediaObject, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GetMedia(ctx, in, opts...)
}

func (m *defaultMedia) GetDownloadURL(ctx context.Context, in *GetDownloadURLRequest, opts ...grpc.CallOption) (*GetDownloadURLResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GetDownloadURL(ctx, in, opts...)
}

func (m *defaultMedia) GetAvatarDisplayURL(ctx context.Context, in *GetAvatarDisplayURLRequest, opts ...grpc.CallOption) (*GetDownloadURLResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GetAvatarDisplayURL(ctx, in, opts...)
}

func (m *defaultMedia) ValidateAvatarMedia(ctx context.Context, in *ValidateAvatarMediaRequest, opts ...grpc.CallOption) (*ValidateMediaResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.ValidateAvatarMedia(ctx, in, opts...)
}

func (m *defaultMedia) ValidateMessageMedia(ctx context.Context, in *ValidateMessageMediaRequest, opts ...grpc.CallOption) (*ValidateMediaResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.ValidateMessageMedia(ctx, in, opts...)
}
