apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - python-executor-rbac.yaml
  - configmap.yaml
  - tempo.yaml
  - otel-collector.yaml
  - langfuse.yaml
  - prometheus-grafana.yaml
  - loki.yaml
  - services.yaml
  - deployments.yaml
  - ingress.yaml
  - cert-manager-issuers.yaml
configMapGenerator:
  - name: agents-im-etc
    namespace: agents-im
    files:
      - etc/user-api.yaml
      - etc/auth-api.yaml
      - etc/friends-api.yaml
      - etc/msg-api.yaml
      - etc/msggateway.yaml
      - etc/groups-api.yaml
      - etc/admin-api.yaml
      - etc/agent-api.yaml
      - etc/msgtransfer.yaml
      - etc/user-rpc.yaml
      - etc/auth-rpc.yaml
      - etc/friends-rpc.yaml
      - etc/groups-rpc.yaml
      - etc/msg-rpc.yaml
      - etc/third-rpc.yaml
      - etc/media-rpc.yaml
      - etc/media-api.yaml
      - etc/admin-rpc.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: Recreate
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull-secret
