apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - python-executor-rbac.yaml
  - configmap.yaml
  - jaeger.yaml
  - services.yaml
  - deployments.yaml
  - ingress.yaml
  - cert-manager-issuers.yaml
configMapGenerator:
  - name: agents-im-etc
    namespace: agents-im
    files:
      - etc/user-api.yaml
      - etc/auth-api.yaml
      - etc/friends-api.yaml
      - etc/message-api.yaml
      - etc/gateway-ws.yaml
      - etc/groups-api.yaml
      - etc/agent-api.yaml
      - etc/message-transfer.yaml
      - etc/user-rpc.yaml
      - etc/auth-rpc.yaml
      - etc/friends-rpc.yaml
      - etc/groups-rpc.yaml
      - etc/message-rpc.yaml
      - etc/mail-rpc.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: Recreate
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull-secret
