// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package authclient

import (
	"context"

	"github.com/wujunhui99/agents_im/service/auth/rpc/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthResponse                  = auth.AuthResponse
	LoginRequest                  = auth.LoginRequest
	RegisterRequest               = auth.RegisterRequest
	RegistrationEmailCodeRequest  = auth.RegistrationEmailCodeRequest
	RegistrationEmailCodeResponse = auth.RegistrationEmailCodeResponse
	ValidateTokenRequest          = auth.ValidateTokenRequest
	ValidateTokenResponse         = auth.ValidateTokenResponse

	Auth interface {
		RequestRegistrationEmailCode(ctx context.Context, in *RegistrationEmailCodeRequest, opts ...grpc.CallOption) (*RegistrationEmailCodeResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
		ParseToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

func (m *defaultAuth) RequestRegistrationEmailCode(ctx context.Context, in *RegistrationEmailCodeRequest, opts ...grpc.CallOption) (*RegistrationEmailCodeResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.RequestRegistrationEmailCode(ctx, in, opts...)
}

func (m *defaultAuth) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAuth) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuth) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultAuth) ParseToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.ParseToken(ctx, in, opts...)
}
