// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	message "github.com/wujunhui99/agents_im/service/message/api/internal/handler/message"
	"github.com/wujunhui99/agents_im/service/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		authenticatedRoutes(serverCtx, []rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/feedback",
				Handler: message.CreateAPIFeedbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations/:conversation_id/ai-hosting",
				Handler: message.GetConversationAIHostingHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/conversations/:conversation_id/ai-hosting",
				Handler: message.UpdateConversationAIHostingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations/:conversation_id/messages",
				Handler: message.PullMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations/:conversation_id/read",
				Handler: message.MarkConversationAsReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations/seqs",
				Handler: message.GetConversationSeqsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/feedback",
				Handler: message.CreateFeedbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/messages",
				Handler: message.SendMessageHandler(serverCtx),
			},
		}),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
