// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/wujunhui99/agents_im/pkg/middleware"
	agent "github.com/wujunhui99/agents_im/service/agent/api/internal/handler/agent"
	"github.com/wujunhui99/agents_im/service/agent/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	routes := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/agents",
			Handler: agent.CreateAgentHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/agents",
			Handler: agent.ListAgentsHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/agents/:agent_id",
			Handler: agent.GetAgentHandler(serverCtx),
		},
		{
			Method:  http.MethodPatch,
			Path:    "/agents/:agent_id",
			Handler: agent.UpdateAgentHandler(serverCtx),
		},
		{
			Method:  http.MethodDelete,
			Path:    "/agents/:agent_id",
			Handler: agent.DeleteAgentHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/agents/:agent_id/definition",
			Handler: agent.GetAgentDefinitionHandler(serverCtx),
		},
		{
			Method:  http.MethodPut,
			Path:    "/agents/:agent_id/definition",
			Handler: agent.UpdateAgentDefinitionHandler(serverCtx),
		},
		{
			Method:  http.MethodPatch,
			Path:    "/agents/:agent_id/status",
			Handler: agent.UpdateAgentStatusHandler(serverCtx),
		},
	}
	routes = authenticatedRoutes(serverCtx, routes)
	server.AddRoutes(
		routes,
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}

// authenticatedRoutes wraps routes with the shared DeviceAuth middleware, which
// rejects tokens whose jti is no longer the active session for their (user, device).
// The middleware reads sub/jti/device claims injected by rest.WithJwt, so it must
// run after it. A nil session store (test/memory wiring) disables the check.
func authenticatedRoutes(serverCtx *svc.ServiceContext, routes []rest.Route) []rest.Route {
	if serverCtx == nil || serverCtx.SessionStore() == nil {
		return routes
	}
	return rest.WithMiddleware(middleware.NewDeviceAuthMiddleware(serverCtx.SessionStore()).Handle, routes...)
}
