// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: service/msg/rpc/msg.proto

package msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_SendMessage_FullMethodName               = "/msg.v1.Msg/SendMessage"
	Msg_AppendStreamMessage_FullMethodName       = "/msg.v1.Msg/AppendStreamMessage"
	Msg_PullMessages_FullMethodName              = "/msg.v1.Msg/PullMessages"
	Msg_GetLastMessageByConvs_FullMethodName     = "/msg.v1.Msg/GetLastMessageByConvs"
	Msg_GetConversationsSeqState_FullMethodName  = "/msg.v1.Msg/GetConversationsSeqState"
	Msg_GetMaxSeqs_FullMethodName                = "/msg.v1.Msg/GetMaxSeqs"
	Msg_GetHasReadSeqs_FullMethodName            = "/msg.v1.Msg/GetHasReadSeqs"
	Msg_MarkConversationAsRead_FullMethodName    = "/msg.v1.Msg/MarkConversationAsRead"
	Msg_RevokeMessage_FullMethodName             = "/msg.v1.Msg/RevokeMessage"
	Msg_DeleteMessages_FullMethodName            = "/msg.v1.Msg/DeleteMessages"
	Msg_ClearConversationMessages_FullMethodName = "/msg.v1.Msg/ClearConversationMessages"
	Msg_GetServerTime_FullMethodName             = "/msg.v1.Msg/GetServerTime"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg 是消息域 RPC（07-message-rpc-redesign §3.1）。
// Phase 0：SendMessage / PullMessages / GetConversationsSeqState / MarkConversationAsRead 已实现（行为对齐旧 message-rpc，
// 仍 PG 写 + seq 分配 + outbox，不动 Kafka）；其余 RPC 先留 stub（返回 Unimplemented），按 07 §8 分阶段落地。
type MsgClient interface {
	// 写
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	AppendStreamMessage(ctx context.Context, in *AppendStreamMessageRequest, opts ...grpc.CallOption) (*AppendStreamMessageResponse, error)
	// 拉历史
	PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error)
	GetLastMessageByConvs(ctx context.Context, in *GetLastMessageByConvsRequest, opts ...grpc.CallOption) (*GetLastMessageByConvsResponse, error)
	// seq 同步
	GetConversationsSeqState(ctx context.Context, in *GetConversationsSeqStateRequest, opts ...grpc.CallOption) (*GetConversationsSeqStateResponse, error)
	GetMaxSeqs(ctx context.Context, in *GetMaxSeqsRequest, opts ...grpc.CallOption) (*GetMaxSeqsResponse, error)
	GetHasReadSeqs(ctx context.Context, in *GetHasReadSeqsRequest, opts ...grpc.CallOption) (*GetHasReadSeqsResponse, error)
	// 已读
	MarkConversationAsRead(ctx context.Context, in *MarkConversationAsReadRequest, opts ...grpc.CallOption) (*MarkConversationAsReadResponse, error)
	// 撤回 / 删除 / 清空（stub）
	RevokeMessage(ctx context.Context, in *RevokeMessageRequest, opts ...grpc.CallOption) (*RevokeMessageResponse, error)
	DeleteMessages(ctx context.Context, in *DeleteMessagesRequest, opts ...grpc.CallOption) (*DeleteMessagesResponse, error)
	ClearConversationMessages(ctx context.Context, in *ClearConversationMessagesRequest, opts ...grpc.CallOption) (*ClearConversationMessagesResponse, error)
	// 时间（stub）
	GetServerTime(ctx context.Context, in *GetServerTimeRequest, opts ...grpc.CallOption) (*GetServerTimeResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Msg_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AppendStreamMessage(ctx context.Context, in *AppendStreamMessageRequest, opts ...grpc.CallOption) (*AppendStreamMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendStreamMessageResponse)
	err := c.cc.Invoke(ctx, Msg_AppendStreamMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullMessagesResponse)
	err := c.cc.Invoke(ctx, Msg_PullMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetLastMessageByConvs(ctx context.Context, in *GetLastMessageByConvsRequest, opts ...grpc.CallOption) (*GetLastMessageByConvsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastMessageByConvsResponse)
	err := c.cc.Invoke(ctx, Msg_GetLastMessageByConvs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetConversationsSeqState(ctx context.Context, in *GetConversationsSeqStateRequest, opts ...grpc.CallOption) (*GetConversationsSeqStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationsSeqStateResponse)
	err := c.cc.Invoke(ctx, Msg_GetConversationsSeqState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetMaxSeqs(ctx context.Context, in *GetMaxSeqsRequest, opts ...grpc.CallOption) (*GetMaxSeqsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMaxSeqsResponse)
	err := c.cc.Invoke(ctx, Msg_GetMaxSeqs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetHasReadSeqs(ctx context.Context, in *GetHasReadSeqsRequest, opts ...grpc.CallOption) (*GetHasReadSeqsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHasReadSeqsResponse)
	err := c.cc.Invoke(ctx, Msg_GetHasReadSeqs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MarkConversationAsRead(ctx context.Context, in *MarkConversationAsReadRequest, opts ...grpc.CallOption) (*MarkConversationAsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkConversationAsReadResponse)
	err := c.cc.Invoke(ctx, Msg_MarkConversationAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeMessage(ctx context.Context, in *RevokeMessageRequest, opts ...grpc.CallOption) (*RevokeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeMessageResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteMessages(ctx context.Context, in *DeleteMessagesRequest, opts ...grpc.CallOption) (*DeleteMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessagesResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClearConversationMessages(ctx context.Context, in *ClearConversationMessagesRequest, opts ...grpc.CallOption) (*ClearConversationMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearConversationMessagesResponse)
	err := c.cc.Invoke(ctx, Msg_ClearConversationMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetServerTime(ctx context.Context, in *GetServerTimeRequest, opts ...grpc.CallOption) (*GetServerTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerTimeResponse)
	err := c.cc.Invoke(ctx, Msg_GetServerTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg 是消息域 RPC（07-message-rpc-redesign §3.1）。
// Phase 0：SendMessage / PullMessages / GetConversationsSeqState / MarkConversationAsRead 已实现（行为对齐旧 message-rpc，
// 仍 PG 写 + seq 分配 + outbox，不动 Kafka）；其余 RPC 先留 stub（返回 Unimplemented），按 07 §8 分阶段落地。
type MsgServer interface {
	// 写
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	AppendStreamMessage(context.Context, *AppendStreamMessageRequest) (*AppendStreamMessageResponse, error)
	// 拉历史
	PullMessages(context.Context, *PullMessagesRequest) (*PullMessagesResponse, error)
	GetLastMessageByConvs(context.Context, *GetLastMessageByConvsRequest) (*GetLastMessageByConvsResponse, error)
	// seq 同步
	GetConversationsSeqState(context.Context, *GetConversationsSeqStateRequest) (*GetConversationsSeqStateResponse, error)
	GetMaxSeqs(context.Context, *GetMaxSeqsRequest) (*GetMaxSeqsResponse, error)
	GetHasReadSeqs(context.Context, *GetHasReadSeqsRequest) (*GetHasReadSeqsResponse, error)
	// 已读
	MarkConversationAsRead(context.Context, *MarkConversationAsReadRequest) (*MarkConversationAsReadResponse, error)
	// 撤回 / 删除 / 清空（stub）
	RevokeMessage(context.Context, *RevokeMessageRequest) (*RevokeMessageResponse, error)
	DeleteMessages(context.Context, *DeleteMessagesRequest) (*DeleteMessagesResponse, error)
	ClearConversationMessages(context.Context, *ClearConversationMessagesRequest) (*ClearConversationMessagesResponse, error)
	// 时间（stub）
	GetServerTime(context.Context, *GetServerTimeRequest) (*GetServerTimeResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMsgServer) AppendStreamMessage(context.Context, *AppendStreamMessageRequest) (*AppendStreamMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendStreamMessage not implemented")
}
func (UnimplementedMsgServer) PullMessages(context.Context, *PullMessagesRequest) (*PullMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullMessages not implemented")
}
func (UnimplementedMsgServer) GetLastMessageByConvs(context.Context, *GetLastMessageByConvsRequest) (*GetLastMessageByConvsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastMessageByConvs not implemented")
}
func (UnimplementedMsgServer) GetConversationsSeqState(context.Context, *GetConversationsSeqStateRequest) (*GetConversationsSeqStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversationsSeqState not implemented")
}
func (UnimplementedMsgServer) GetMaxSeqs(context.Context, *GetMaxSeqsRequest) (*GetMaxSeqsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMaxSeqs not implemented")
}
func (UnimplementedMsgServer) GetHasReadSeqs(context.Context, *GetHasReadSeqsRequest) (*GetHasReadSeqsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHasReadSeqs not implemented")
}
func (UnimplementedMsgServer) MarkConversationAsRead(context.Context, *MarkConversationAsReadRequest) (*MarkConversationAsReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkConversationAsRead not implemented")
}
func (UnimplementedMsgServer) RevokeMessage(context.Context, *RevokeMessageRequest) (*RevokeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMessage not implemented")
}
func (UnimplementedMsgServer) DeleteMessages(context.Context, *DeleteMessagesRequest) (*DeleteMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessages not implemented")
}
func (UnimplementedMsgServer) ClearConversationMessages(context.Context, *ClearConversationMessagesRequest) (*ClearConversationMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearConversationMessages not implemented")
}
func (UnimplementedMsgServer) GetServerTime(context.Context, *GetServerTimeRequest) (*GetServerTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerTime not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AppendStreamMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendStreamMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AppendStreamMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AppendStreamMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AppendStreamMessage(ctx, req.(*AppendStreamMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PullMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PullMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_PullMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PullMessages(ctx, req.(*PullMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetLastMessageByConvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastMessageByConvsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetLastMessageByConvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GetLastMessageByConvs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetLastMessageByConvs(ctx, req.(*GetLastMessageByConvsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetConversationsSeqState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationsSeqStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetConversationsSeqState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GetConversationsSeqState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetConversationsSeqState(ctx, req.(*GetConversationsSeqStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetMaxSeqs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaxSeqsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetMaxSeqs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GetMaxSeqs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetMaxSeqs(ctx, req.(*GetMaxSeqsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetHasReadSeqs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHasReadSeqsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetHasReadSeqs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GetHasReadSeqs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetHasReadSeqs(ctx, req.(*GetHasReadSeqsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MarkConversationAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkConversationAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MarkConversationAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MarkConversationAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MarkConversationAsRead(ctx, req.(*MarkConversationAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeMessage(ctx, req.(*RevokeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteMessages(ctx, req.(*DeleteMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClearConversationMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearConversationMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClearConversationMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClearConversationMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClearConversationMessages(ctx, req.(*ClearConversationMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetServerTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetServerTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GetServerTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetServerTime(ctx, req.(*GetServerTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Msg_SendMessage_Handler,
		},
		{
			MethodName: "AppendStreamMessage",
			Handler:    _Msg_AppendStreamMessage_Handler,
		},
		{
			MethodName: "PullMessages",
			Handler:    _Msg_PullMessages_Handler,
		},
		{
			MethodName: "GetLastMessageByConvs",
			Handler:    _Msg_GetLastMessageByConvs_Handler,
		},
		{
			MethodName: "GetConversationsSeqState",
			Handler:    _Msg_GetConversationsSeqState_Handler,
		},
		{
			MethodName: "GetMaxSeqs",
			Handler:    _Msg_GetMaxSeqs_Handler,
		},
		{
			MethodName: "GetHasReadSeqs",
			Handler:    _Msg_GetHasReadSeqs_Handler,
		},
		{
			MethodName: "MarkConversationAsRead",
			Handler:    _Msg_MarkConversationAsRead_Handler,
		},
		{
			MethodName: "RevokeMessage",
			Handler:    _Msg_RevokeMessage_Handler,
		},
		{
			MethodName: "DeleteMessages",
			Handler:    _Msg_DeleteMessages_Handler,
		},
		{
			MethodName: "ClearConversationMessages",
			Handler:    _Msg_ClearConversationMessages_Handler,
		},
		{
			MethodName: "GetServerTime",
			Handler:    _Msg_GetServerTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/msg/rpc/msg.proto",
}
