// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: service/friends/rpc/friends.proto

package friends

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Friends_AddFriend_FullMethodName           = "/friends.v1.Friends/AddFriend"
	Friends_DeleteFriend_FullMethodName        = "/friends.v1.Friends/DeleteFriend"
	Friends_ListFriends_FullMethodName         = "/friends.v1.Friends/ListFriends"
	Friends_GetFriendship_FullMethodName       = "/friends.v1.Friends/GetFriendship"
	Friends_ListFriendRequests_FullMethodName  = "/friends.v1.Friends/ListFriendRequests"
	Friends_AcceptFriendRequest_FullMethodName = "/friends.v1.Friends/AcceptFriendRequest"
	Friends_RejectFriendRequest_FullMethodName = "/friends.v1.Friends/RejectFriendRequest"
	Friends_EnsureFriendship_FullMethodName    = "/friends.v1.Friends/EnsureFriendship"
)

// FriendsClient is the client API for Friends service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendsClient interface {
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
	DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	GetFriendship(ctx context.Context, in *GetFriendshipRequest, opts ...grpc.CallOption) (*GetFriendshipResponse, error)
	ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error)
	AcceptFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error)
	RejectFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error)
	// EnsureFriendship 幂等地建立 user_id <-> friend_id 的双向 accepted 好友关系（不触发请求/审批流）。
	// 供默认助手开通（user-rpc 装配）与 agent.create 工具路径（agent-rpc）跨域建好友使用——
	// 取代旧 internal/repository.EnsureAcceptedFriendship。调用方负责账号存在性（friends-rpc 是叶子，
	// 不读 accounts）。重复调用不重置 created_at。
	EnsureFriendship(ctx context.Context, in *EnsureFriendshipRequest, opts ...grpc.CallOption) (*EnsureFriendshipResponse, error)
}

type friendsClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendsClient(cc grpc.ClientConnInterface) FriendsClient {
	return &friendsClient{cc}
}

func (c *friendsClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFriendResponse)
	err := c.cc.Invoke(ctx, Friends_AddFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFriendResponse)
	err := c.cc.Invoke(ctx, Friends_DeleteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, Friends_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) GetFriendship(ctx context.Context, in *GetFriendshipRequest, opts ...grpc.CallOption) (*GetFriendshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendshipResponse)
	err := c.cc.Invoke(ctx, Friends_GetFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendRequestsResponse)
	err := c.cc.Invoke(ctx, Friends_ListFriendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) AcceptFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendRequestDecisionResponse)
	err := c.cc.Invoke(ctx, Friends_AcceptFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) RejectFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendRequestDecisionResponse)
	err := c.cc.Invoke(ctx, Friends_RejectFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) EnsureFriendship(ctx context.Context, in *EnsureFriendshipRequest, opts ...grpc.CallOption) (*EnsureFriendshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureFriendshipResponse)
	err := c.cc.Invoke(ctx, Friends_EnsureFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendsServer is the server API for Friends service.
// All implementations must embed UnimplementedFriendsServer
// for forward compatibility.
type FriendsServer interface {
	AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error)
	DeleteFriend(context.Context, *DeleteFriendRequest) (*DeleteFriendResponse, error)
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	GetFriendship(context.Context, *GetFriendshipRequest) (*GetFriendshipResponse, error)
	ListFriendRequests(context.Context, *ListFriendRequestsRequest) (*ListFriendRequestsResponse, error)
	AcceptFriendRequest(context.Context, *FriendRequestDecisionRequest) (*FriendRequestDecisionResponse, error)
	RejectFriendRequest(context.Context, *FriendRequestDecisionRequest) (*FriendRequestDecisionResponse, error)
	// EnsureFriendship 幂等地建立 user_id <-> friend_id 的双向 accepted 好友关系（不触发请求/审批流）。
	// 供默认助手开通（user-rpc 装配）与 agent.create 工具路径（agent-rpc）跨域建好友使用——
	// 取代旧 internal/repository.EnsureAcceptedFriendship。调用方负责账号存在性（friends-rpc 是叶子，
	// 不读 accounts）。重复调用不重置 created_at。
	EnsureFriendship(context.Context, *EnsureFriendshipRequest) (*EnsureFriendshipResponse, error)
	mustEmbedUnimplementedFriendsServer()
}

// UnimplementedFriendsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendsServer struct{}

func (UnimplementedFriendsServer) AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFriend not implemented")
}
func (UnimplementedFriendsServer) DeleteFriend(context.Context, *DeleteFriendRequest) (*DeleteFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (UnimplementedFriendsServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedFriendsServer) GetFriendship(context.Context, *GetFriendshipRequest) (*GetFriendshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendship not implemented")
}
func (UnimplementedFriendsServer) ListFriendRequests(context.Context, *ListFriendRequestsRequest) (*ListFriendRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriendRequests not implemented")
}
func (UnimplementedFriendsServer) AcceptFriendRequest(context.Context, *FriendRequestDecisionRequest) (*FriendRequestDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (UnimplementedFriendsServer) RejectFriendRequest(context.Context, *FriendRequestDecisionRequest) (*FriendRequestDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectFriendRequest not implemented")
}
func (UnimplementedFriendsServer) EnsureFriendship(context.Context, *EnsureFriendshipRequest) (*EnsureFriendshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureFriendship not implemented")
}
func (UnimplementedFriendsServer) mustEmbedUnimplementedFriendsServer() {}
func (UnimplementedFriendsServer) testEmbeddedByValue()                 {}

// UnsafeFriendsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendsServer will
// result in compilation errors.
type UnsafeFriendsServer interface {
	mustEmbedUnimplementedFriendsServer()
}

func RegisterFriendsServer(s grpc.ServiceRegistrar, srv FriendsServer) {
	// If the following call panics, it indicates UnimplementedFriendsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Friends_ServiceDesc, srv)
}

func _Friends_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_AddFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).AddFriend(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_DeleteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).DeleteFriend(ctx, req.(*DeleteFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_GetFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).GetFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_GetFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).GetFriendship(ctx, req.(*GetFriendshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_ListFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).ListFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_ListFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).ListFriendRequests(ctx, req.(*ListFriendRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequestDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_AcceptFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).AcceptFriendRequest(ctx, req.(*FriendRequestDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_RejectFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequestDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).RejectFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_RejectFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).RejectFriendRequest(ctx, req.(*FriendRequestDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_EnsureFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureFriendshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).EnsureFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_EnsureFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).EnsureFriendship(ctx, req.(*EnsureFriendshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Friends_ServiceDesc is the grpc.ServiceDesc for Friends service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friends_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friends.v1.Friends",
	HandlerType: (*FriendsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFriend",
			Handler:    _Friends_AddFriend_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _Friends_DeleteFriend_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _Friends_ListFriends_Handler,
		},
		{
			MethodName: "GetFriendship",
			Handler:    _Friends_GetFriendship_Handler,
		},
		{
			MethodName: "ListFriendRequests",
			Handler:    _Friends_ListFriendRequests_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _Friends_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "RejectFriendRequest",
			Handler:    _Friends_RejectFriendRequest_Handler,
		},
		{
			MethodName: "EnsureFriendship",
			Handler:    _Friends_EnsureFriendship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/friends/rpc/friends.proto",
}
