// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service/msggateway/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchPushOneMsgReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PushToUserIds  []string               `protobuf:"bytes,2,rep,name=push_to_user_ids,json=pushToUserIds,proto3" json:"push_to_user_ids,omitempty"`
	// event_json 是 pkg/gateway/delivery.Event（message_received）的 JSON 编码。
	// 携 JSON 而非把 20+ 消息字段重建成 proto：与现有 dispatcher 保持线兼容，
	// 也避免在 D6（Kafka wire 切 proto MsgData）落地前提前造型。
	EventJson     []byte `protobuf:"bytes,3,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPushOneMsgReq) Reset() {
	*x = BatchPushOneMsgReq{}
	mi := &file_service_msggateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushOneMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushOneMsgReq) ProtoMessage() {}

func (x *BatchPushOneMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_msggateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushOneMsgReq.ProtoReflect.Descriptor instead.
func (*BatchPushOneMsgReq) Descriptor() ([]byte, []int) {
	return file_service_msggateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *BatchPushOneMsgReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *BatchPushOneMsgReq) GetPushToUserIds() []string {
	if x != nil {
		return x.PushToUserIds
	}
	return nil
}

func (x *BatchPushOneMsgReq) GetEventJson() []byte {
	if x != nil {
		return x.EventJson
	}
	return nil
}

type BatchPushOneMsgResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Recipients    []*RecipientDeliveryResult `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPushOneMsgResp) Reset() {
	*x = BatchPushOneMsgResp{}
	mi := &file_service_msggateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushOneMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushOneMsgResp) ProtoMessage() {}

func (x *BatchPushOneMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_msggateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushOneMsgResp.ProtoReflect.Descriptor instead.
func (*BatchPushOneMsgResp) Descriptor() ([]byte, []int) {
	return file_service_msggateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *BatchPushOneMsgResp) GetRecipients() []*RecipientDeliveryResult {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type RecipientDeliveryResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// status 取 pkg/gateway/delivery.Status*：delivered / offline / failed / routed。
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientDeliveryResult) Reset() {
	*x = RecipientDeliveryResult{}
	mi := &file_service_msggateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientDeliveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientDeliveryResult) ProtoMessage() {}

func (x *RecipientDeliveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_msggateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientDeliveryResult.ProtoReflect.Descriptor instead.
func (*RecipientDeliveryResult) Descriptor() ([]byte, []int) {
	return file_service_msggateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RecipientDeliveryResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecipientDeliveryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecipientDeliveryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_service_msggateway_gateway_proto protoreflect.FileDescriptor

const file_service_msggateway_gateway_proto_rawDesc = "" +
	"\n" +
	" service/msggateway/gateway.proto\x12\n" +
	"gateway.v1\"\x85\x01\n" +
	"\x12BatchPushOneMsgReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12'\n" +
	"\x10push_to_user_ids\x18\x02 \x03(\tR\rpushToUserIds\x12\x1d\n" +
	"\n" +
	"event_json\x18\x03 \x01(\fR\teventJson\"Z\n" +
	"\x13BatchPushOneMsgResp\x12C\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2#.gateway.v1.RecipientDeliveryResultR\n" +
	"recipients\"`\n" +
	"\x17RecipientDeliveryResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2d\n" +
	"\x0eGatewayService\x12R\n" +
	"\x0fBatchPushOneMsg\x12\x1e.gateway.v1.BatchPushOneMsgReq\x1a\x1f.gateway.v1.BatchPushOneMsgRespB>Z<github.com/wujunhui99/agents_im/service/msggateway/gatewaypbb\x06proto3"

var (
	file_service_msggateway_gateway_proto_rawDescOnce sync.Once
	file_service_msggateway_gateway_proto_rawDescData []byte
)

func file_service_msggateway_gateway_proto_rawDescGZIP() []byte {
	file_service_msggateway_gateway_proto_rawDescOnce.Do(func() {
		file_service_msggateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_msggateway_gateway_proto_rawDesc), len(file_service_msggateway_gateway_proto_rawDesc)))
	})
	return file_service_msggateway_gateway_proto_rawDescData
}

var file_service_msggateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_msggateway_gateway_proto_goTypes = []any{
	(*BatchPushOneMsgReq)(nil),      // 0: gateway.v1.BatchPushOneMsgReq
	(*BatchPushOneMsgResp)(nil),     // 1: gateway.v1.BatchPushOneMsgResp
	(*RecipientDeliveryResult)(nil), // 2: gateway.v1.RecipientDeliveryResult
}
var file_service_msggateway_gateway_proto_depIdxs = []int32{
	2, // 0: gateway.v1.BatchPushOneMsgResp.recipients:type_name -> gateway.v1.RecipientDeliveryResult
	0, // 1: gateway.v1.GatewayService.BatchPushOneMsg:input_type -> gateway.v1.BatchPushOneMsgReq
	1, // 2: gateway.v1.GatewayService.BatchPushOneMsg:output_type -> gateway.v1.BatchPushOneMsgResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_msggateway_gateway_proto_init() }
func file_service_msggateway_gateway_proto_init() {
	if File_service_msggateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_msggateway_gateway_proto_rawDesc), len(file_service_msggateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_msggateway_gateway_proto_goTypes,
		DependencyIndexes: file_service_msggateway_gateway_proto_depIdxs,
		MessageInfos:      file_service_msggateway_gateway_proto_msgTypes,
	}.Build()
	File_service_msggateway_gateway_proto = out.File
	file_service_msggateway_gateway_proto_goTypes = nil
	file_service_msggateway_gateway_proto_depIdxs = nil
}
