// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendshipsFieldNames          = builder.RawFieldNames(&Friendships{}, true)
	friendshipsRows                = strings.Join(friendshipsFieldNames, ",")
	friendshipsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendshipsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	friendshipsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(friendshipsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	friendshipsModel interface {
		Insert(ctx context.Context, data *Friendships) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friendships, error)
		FindOneByAccountIdFriendAccountId(ctx context.Context, accountId string, friendAccountId string) (*Friendships, error)
		Update(ctx context.Context, data *Friendships) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendshipsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Friendships struct {
		AccountId       string    `db:"account_id"`
		FriendAccountId string    `db:"friend_account_id"`
		Status          int64     `db:"status"`
		CreatedAt       time.Time `db:"created_at"`
		UpdatedAt       time.Time `db:"updated_at"`
		Id              int64     `db:"id"`
	}
)

func newFriendshipsModel(conn sqlx.SqlConn) *defaultFriendshipsModel {
	return &defaultFriendshipsModel{
		conn:  conn,
		table: `"public"."friendships"`,
	}
}

func (m *defaultFriendshipsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFriendshipsModel) FindOne(ctx context.Context, id int64) (*Friendships, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", friendshipsRows, m.table)
	var resp Friendships
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendshipsModel) FindOneByAccountIdFriendAccountId(ctx context.Context, accountId string, friendAccountId string) (*Friendships, error) {
	var resp Friendships
	query := fmt.Sprintf("select %s from %s where account_id = $1 and friend_account_id = $2 limit 1", friendshipsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, accountId, friendAccountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendshipsModel) Insert(ctx context.Context, data *Friendships) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, friendshipsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.FriendAccountId, data.Status)
	return ret, err
}

func (m *defaultFriendshipsModel) Update(ctx context.Context, newData *Friendships) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, friendshipsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AccountId, newData.FriendAccountId, newData.Status)
	return err
}

func (m *defaultFriendshipsModel) tableName() string {
	return m.table
}
