// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	groups "github.com/wujunhui99/agents_im/service/groups/api/internal/handler/groups"
	"github.com/wujunhui99/agents_im/service/groups/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/groups",
				Handler: groups.CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups",
				Handler: groups.ListGroupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups/:group_id",
				Handler: groups.GetGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/groups/:group_id",
				Handler: groups.UpdateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/groups/:group_id/members",
				Handler: groups.AddMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups/:group_id/members",
				Handler: groups.ListMembersHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/groups/:group_id/members/:user_id",
				Handler: groups.KickMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/groups/:group_id/members/me",
				Handler: groups.LeaveGroupHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
