FROM alpine:3.20

ARG KUBECTL_VERSION=v1.32.0

RUN apk add --no-cache \
    bash \
    openssh-client \
    tar \
    curl \
    docker-cli \
    docker-cli-compose \
    postgresql-client \
  && curl -fsSL -o /usr/local/bin/kubectl "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
  && chmod +x /usr/local/bin/kubectl \
  && kubectl version --client=true
