// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: friends.proto

package friendsclient

import (
	"context"

	friends "github.com/wujunhui99/agents_im/service/friends/rpc/friends"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequest              = friends.AddFriendRequest
	AddFriendResponse             = friends.AddFriendResponse
	DeleteFriendRequest           = friends.DeleteFriendRequest
	DeleteFriendResponse          = friends.DeleteFriendResponse
	FriendProfile                 = friends.FriendProfile
	FriendRequestDecisionRequest  = friends.FriendRequestDecisionRequest
	FriendRequestDecisionResponse = friends.FriendRequestDecisionResponse
	Friendship                    = friends.Friendship
	GetFriendshipRequest          = friends.GetFriendshipRequest
	GetFriendshipResponse         = friends.GetFriendshipResponse
	ListFriendRequestsRequest     = friends.ListFriendRequestsRequest
	ListFriendRequestsResponse    = friends.ListFriendRequestsResponse
	ListFriendsRequest            = friends.ListFriendsRequest
	ListFriendsResponse           = friends.ListFriendsResponse

	Friends interface {
		AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
		ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
		GetFriendship(ctx context.Context, in *GetFriendshipRequest, opts ...grpc.CallOption) (*GetFriendshipResponse, error)
		ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error)
		AcceptFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error)
		RejectFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error)
	}

	defaultFriends struct {
		cli zrpc.Client
	}
)

func NewFriends(cli zrpc.Client) Friends {
	return &defaultFriends{
		cli: cli,
	}
}

func (m *defaultFriends) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.AddFriend(ctx, in, opts...)
}

func (m *defaultFriends) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

func (m *defaultFriends) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.ListFriends(ctx, in, opts...)
}

func (m *defaultFriends) GetFriendship(ctx context.Context, in *GetFriendshipRequest, opts ...grpc.CallOption) (*GetFriendshipResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.GetFriendship(ctx, in, opts...)
}

func (m *defaultFriends) ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.ListFriendRequests(ctx, in, opts...)
}

func (m *defaultFriends) AcceptFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.AcceptFriendRequest(ctx, in, opts...)
}

func (m *defaultFriends) RejectFriendRequest(ctx context.Context, in *FriendRequestDecisionRequest, opts ...grpc.CallOption) (*FriendRequestDecisionResponse, error) {
	client := friends.NewFriendsClient(m.cli.Conn())
	return client.RejectFriendRequest(ctx, in, opts...)
}
