// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthData struct {
	UserID        string `json:"user_id"`
	Identifier    string `json:"identifier"`
	Email         string `json:"email,optional"`
	DisplayName   string `json:"display_name,optional"`
	Name          string `json:"name,optional"`
	Gender        string `json:"gender,optional"`
	BirthDate     string `json:"birth_date,optional"`
	Region        string `json:"region,optional"`
	AccountType   string `json:"account_type,optional"`
	AvatarMediaID string `json:"avatar_media_id,optional"`
	AvatarURL     string `json:"avatar_url,optional"`
	Token         string `json:"token"`
	ExpiresAt     string `json:"expires_at"`
}

type AuthResp struct {
	Code    string   `json:"code"`
	Message string   `json:"message"`
	Data    AuthData `json:"data"`
}

type LoginReq struct {
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
}

type RegisterReq struct {
	Identifier            string `json:"identifier"`
	Email                 string `json:"email"`
	EmailVerificationCode string `json:"email_verification_code"`
	Password              string `json:"password"`
	DisplayName           string `json:"display_name,optional"`
	Name                  string `json:"name,optional"`
	Gender                string `json:"gender,optional"`
	BirthDate             string `json:"birth_date,optional"`
	Region                string `json:"region,optional"`
}

type RegistrationEmailCodeData struct {
	Email         string `json:"email"`
	ExpireMinutes int    `json:"expire_minutes"`
}

type RegistrationEmailCodeReq struct {
	Email string `json:"email"`
}

type RegistrationEmailCodeResp struct {
	Code    string                    `json:"code"`
	Message string                    `json:"message"`
	Data    RegistrationEmailCodeData `json:"data"`
}

type ValidateTokenData struct {
	Valid      bool   `json:"valid"`
	UserID     string `json:"user_id"`
	Identifier string `json:"identifier"`
	ExpiresAt  string `json:"expires_at"`
}

type ValidateTokenReq struct {
	Token string `json:"token"`
}

type ValidateTokenResp struct {
	Code    string            `json:"code"`
	Message string            `json:"message"`
	Data    ValidateTokenData `json:"data"`
}
