// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: groups.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/internal/rpcgen/groups/internal/logic"
	"github.com/wujunhui99/agents_im/internal/rpcgen/groups/internal/svc"
	"github.com/wujunhui99/agents_im/proto/groupspb"
)

type GroupsServiceServer struct {
	svcCtx *svc.ServiceContext
	groupspb.UnimplementedGroupsServiceServer
}

func NewGroupsServiceServer(svcCtx *svc.ServiceContext) *GroupsServiceServer {
	return &GroupsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupsServiceServer) CreateGroup(ctx context.Context, in *groupspb.CreateGroupRequest) (*groupspb.GroupResponse, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupsServiceServer) GetGroup(ctx context.Context, in *groupspb.GetGroupRequest) (*groupspb.GroupResponse, error) {
	l := logic.NewGetGroupLogic(ctx, s.svcCtx)
	return l.GetGroup(in)
}

func (s *GroupsServiceServer) AddMember(ctx context.Context, in *groupspb.AddMemberRequest) (*groupspb.MemberResponse, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

func (s *GroupsServiceServer) JoinGroup(ctx context.Context, in *groupspb.JoinGroupRequest) (*groupspb.MemberResponse, error) {
	l := logic.NewJoinGroupLogic(ctx, s.svcCtx)
	return l.JoinGroup(in)
}

func (s *GroupsServiceServer) LeaveGroup(ctx context.Context, in *groupspb.LeaveGroupRequest) (*groupspb.MemberResponse, error) {
	l := logic.NewLeaveGroupLogic(ctx, s.svcCtx)
	return l.LeaveGroup(in)
}

func (s *GroupsServiceServer) ListMembers(ctx context.Context, in *groupspb.ListMembersRequest) (*groupspb.ListMembersResponse, error) {
	l := logic.NewListMembersLogic(ctx, s.svcCtx)
	return l.ListMembers(in)
}
