// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/proto/userpb"
	"github.com/wujunhui99/agents_im/service/user/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/user/rpc/internal/svc"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) CreateUser(ctx context.Context, in *userpb.CreateUserRequest) (*userpb.UserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServiceServer) GetUserByIdentifier(ctx context.Context, in *userpb.GetUserByIdentifierRequest) (*userpb.UserResponse, error) {
	l := logic.NewGetUserByIdentifierLogic(ctx, s.svcCtx)
	return l.GetUserByIdentifier(in)
}

func (s *UserServiceServer) ExistsByIdentifier(ctx context.Context, in *userpb.ExistsByIdentifierRequest) (*userpb.ExistsByIdentifierResponse, error) {
	l := logic.NewExistsByIdentifierLogic(ctx, s.svcCtx)
	return l.ExistsByIdentifier(in)
}

func (s *UserServiceServer) GetUserByID(ctx context.Context, in *userpb.GetUserByIDRequest) (*userpb.UserResponse, error) {
	l := logic.NewGetUserByIDLogic(ctx, s.svcCtx)
	return l.GetUserByID(in)
}

func (s *UserServiceServer) UpdateUserProfile(ctx context.Context, in *userpb.UpdateUserProfileRequest) (*userpb.UserResponse, error) {
	l := logic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}
