// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/service/user/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/user/rpc/internal/svc"
	"github.com/wujunhui99/agents_im/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *user.CreateUserRequest) (*user.UserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) GetUserByIdentifier(ctx context.Context, in *user.GetUserByIdentifierRequest) (*user.UserResponse, error) {
	l := logic.NewGetUserByIdentifierLogic(ctx, s.svcCtx)
	return l.GetUserByIdentifier(in)
}

func (s *UserServer) ExistsByIdentifier(ctx context.Context, in *user.ExistsByIdentifierRequest) (*user.ExistsByIdentifierResponse, error) {
	l := logic.NewExistsByIdentifierLogic(ctx, s.svcCtx)
	return l.ExistsByIdentifier(in)
}

func (s *UserServer) GetUserByID(ctx context.Context, in *user.GetUserByIDRequest) (*user.UserResponse, error) {
	l := logic.NewGetUserByIDLogic(ctx, s.svcCtx)
	return l.GetUserByID(in)
}

func (s *UserServer) GetUsersByIDs(ctx context.Context, in *user.GetUsersByIDsRequest) (*user.GetUsersByIDsResponse, error) {
	l := logic.NewGetUsersByIDsLogic(ctx, s.svcCtx)
	return l.GetUsersByIDs(in)
}

func (s *UserServer) SearchAccounts(ctx context.Context, in *user.SearchAccountsRequest) (*user.SearchAccountsResponse, error) {
	l := logic.NewSearchAccountsLogic(ctx, s.svcCtx)
	return l.SearchAccounts(in)
}

func (s *UserServer) CountAccounts(ctx context.Context, in *user.CountAccountsRequest) (*user.CountAccountsResponse, error) {
	l := logic.NewCountAccountsLogic(ctx, s.svcCtx)
	return l.CountAccounts(in)
}

func (s *UserServer) UpdateUserProfile(ctx context.Context, in *user.UpdateUserProfileRequest) (*user.UserResponse, error) {
	l := logic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}

func (s *UserServer) UpdateUserAvatar(ctx context.Context, in *user.UpdateUserAvatarRequest) (*user.UserResponse, error) {
	l := logic.NewUpdateUserAvatarLogic(ctx, s.svcCtx)
	return l.UpdateUserAvatar(in)
}

// CreateTestAccount 创建管理后台用的测试账户（account_type=test，不绑定邮箱）。
func (s *UserServer) CreateTestAccount(ctx context.Context, in *user.CreateTestAccountRequest) (*user.CreateTestAccountResponse, error) {
	l := logic.NewCreateTestAccountLogic(ctx, s.svcCtx)
	return l.CreateTestAccount(in)
}
