// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	msg "github.com/wujunhui99/agents_im/service/msg/api/internal/handler/msg"
	"github.com/wujunhui99/agents_im/service/msg/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.DeviceAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/feedback",
					Handler: msg.CreateFeedbackHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/conversations/:conversation_id/ai-hosting",
					Handler: msg.GetConversationAIHostingHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/conversations/:conversation_id/ai-hosting",
					Handler: msg.UpdateConversationAIHostingHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/conversations/:conversation_id/messages",
					Handler: msg.PullMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/conversations/:conversation_id/read",
					Handler: msg.MarkConversationAsReadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/conversations/seqs",
					Handler: msg.GetConversationSeqsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/messages",
					Handler: msg.SendMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
