// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service/groups/rpc/groups.proto

package groups

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Announcement    string                 `protobuf:"bytes,4,opt,name=announcement,proto3" json:"announcement,omitempty"`
	AvatarMediaId   string                 `protobuf:"bytes,5,opt,name=avatar_media_id,json=avatarMediaId,proto3" json:"avatar_media_id,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatorUserId   string                 `protobuf:"bytes,7,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id,omitempty"`
	CurrentUserRole string                 `protobuf:"bytes,8,opt,name=current_user_role,json=currentUserRole,proto3" json:"current_user_role,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *Group) GetAvatarMediaId() string {
	if x != nil {
		return x.AvatarMediaId
	}
	return ""
}

func (x *Group) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Group) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *Group) GetCurrentUserRole() string {
	if x != nil {
		return x.CurrentUserRole
	}
	return ""
}

func (x *Group) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Group) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        string                 `protobuf:"bytes,6,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	Identifier    string                 `protobuf:"bytes,7,opt,name=identifier,proto3" json:"identifier,omitempty"`
	DisplayName   string                 `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	AvatarMediaId string                 `protobuf:"bytes,10,opt,name=avatar_media_id,json=avatarMediaId,proto3" json:"avatar_media_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,11,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupMember) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GroupMember) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *GroupMember) GetLeftAt() string {
	if x != nil {
		return x.LeftAt
	}
	return ""
}

func (x *GroupMember) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *GroupMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GroupMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupMember) GetAvatarMediaId() string {
	if x != nil {
		return x.AvatarMediaId
	}
	return ""
}

func (x *GroupMember) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorUserId string                 `protobuf:"bytes,1,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MemberUserIds []string               `protobuf:"bytes,4,rep,name=member_user_ids,json=memberUserIds,proto3" json:"member_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRequest) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberUserIds() []string {
	if x != nil {
		return x.MemberUserIds
	}
	return nil
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{3}
}

func (x *ListGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGroupRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type UpdateGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId string                 `protobuf:"bytes,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Announcement   string                 `protobuf:"bytes,5,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

type AddMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId string                 `protobuf:"bytes,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{6}
}

func (x *AddMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddMemberRequest) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LeaveGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type KickMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId string                 `protobuf:"bytes,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KickMemberRequest) Reset() {
	*x = KickMemberRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberRequest) ProtoMessage() {}

func (x *KickMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberRequest.ProtoReflect.Descriptor instead.
func (*KickMemberRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{9}
}

func (x *KickMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *KickMemberRequest) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *KickMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListMembersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListMembersRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type GroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{11}
}

func (x *GroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{12}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type MemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *GroupMember           `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	AlreadyMember bool                   `protobuf:"varint,2,opt,name=already_member,json=alreadyMember,proto3" json:"already_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberResponse) Reset() {
	*x = MemberResponse{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberResponse) ProtoMessage() {}

func (x *MemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberResponse.ProtoReflect.Descriptor instead.
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{13}
}

func (x *MemberResponse) GetMember() *GroupMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *MemberResponse) GetAlreadyMember() bool {
	if x != nil {
		return x.AlreadyMember
	}
	return false
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Members       []*GroupMember         `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{14}
}

func (x *ListMembersResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListMembersResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{15}
}

func (x *IsMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *IsMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_service_groups_rpc_groups_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_groups_rpc_groups_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_service_groups_rpc_groups_proto_rawDescGZIP(), []int{16}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

var File_service_groups_rpc_groups_proto protoreflect.FileDescriptor

const file_service_groups_rpc_groups_proto_rawDesc = "" +
	"\n" +
	"\x1fservice/groups/rpc/groups.proto\x12\tgroups.v1\"\xd5\x02\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\fannouncement\x18\x04 \x01(\tR\fannouncement\x12&\n" +
	"\x0favatar_media_id\x18\x05 \x01(\tR\ravatarMediaId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12&\n" +
	"\x0fcreator_user_id\x18\a \x01(\tR\rcreatorUserId\x12*\n" +
	"\x11current_user_role\x18\b \x01(\tR\x0fcurrentUserRole\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xbf\x02\n" +
	"\vGroupMember\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\tR\bjoinedAt\x12\x17\n" +
	"\aleft_at\x18\x06 \x01(\tR\x06leftAt\x12\x1e\n" +
	"\n" +
	"identifier\x18\a \x01(\tR\n" +
	"identifier\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12&\n" +
	"\x0favatar_media_id\x18\n" +
	" \x01(\tR\ravatarMediaId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\v \x01(\tR\tavatarUrl\"\x9a\x01\n" +
	"\x12CreateGroupRequest\x12&\n" +
	"\x0fcreator_user_id\x18\x01 \x01(\tR\rcreatorUserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x0fmember_user_ids\x18\x04 \x03(\tR\rmemberUserIds\",\n" +
	"\x11ListGroupsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"X\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\"\xb3\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\tR\x0eoperatorUserId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\fannouncement\x18\x05 \x01(\tR\fannouncement\"p\n" +
	"\x10AddMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\tR\x0eoperatorUserId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"F\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"q\n" +
	"\x11KickMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\tR\x0eoperatorUserId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"[\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\"7\n" +
	"\rGroupResponse\x12&\n" +
	"\x05group\x18\x01 \x01(\v2\x10.groups.v1.GroupR\x05group\">\n" +
	"\x12ListGroupsResponse\x12(\n" +
	"\x06groups\x18\x01 \x03(\v2\x10.groups.v1.GroupR\x06groups\"g\n" +
	"\x0eMemberResponse\x12.\n" +
	"\x06member\x18\x01 \x01(\v2\x16.groups.v1.GroupMemberR\x06member\x12%\n" +
	"\x0ealready_member\x18\x02 \x01(\bR\ralreadyMember\"b\n" +
	"\x13ListMembersResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x120\n" +
	"\amembers\x18\x02 \x03(\v2\x16.groups.v1.GroupMemberR\amembers\"E\n" +
	"\x0fIsMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember2\xd0\x05\n" +
	"\x06Groups\x12F\n" +
	"\vCreateGroup\x12\x1d.groups.v1.CreateGroupRequest\x1a\x18.groups.v1.GroupResponse\x12I\n" +
	"\n" +
	"ListGroups\x12\x1c.groups.v1.ListGroupsRequest\x1a\x1d.groups.v1.ListGroupsResponse\x12@\n" +
	"\bGetGroup\x12\x1a.groups.v1.GetGroupRequest\x1a\x18.groups.v1.GroupResponse\x12F\n" +
	"\vUpdateGroup\x12\x1d.groups.v1.UpdateGroupRequest\x1a\x18.groups.v1.GroupResponse\x12C\n" +
	"\tAddMember\x12\x1b.groups.v1.AddMemberRequest\x1a\x19.groups.v1.MemberResponse\x12C\n" +
	"\tJoinGroup\x12\x1b.groups.v1.JoinGroupRequest\x1a\x19.groups.v1.MemberResponse\x12E\n" +
	"\n" +
	"LeaveGroup\x12\x1c.groups.v1.LeaveGroupRequest\x1a\x19.groups.v1.MemberResponse\x12E\n" +
	"\n" +
	"KickMember\x12\x1c.groups.v1.KickMemberRequest\x1a\x19.groups.v1.MemberResponse\x12L\n" +
	"\vListMembers\x12\x1d.groups.v1.ListMembersRequest\x1a\x1e.groups.v1.ListMembersResponse\x12C\n" +
	"\bIsMember\x12\x1a.groups.v1.IsMemberRequest\x1a\x1b.groups.v1.IsMemberResponseB;Z9github.com/wujunhui99/agents_im/service/groups/rpc/groupsb\x06proto3"

var (
	file_service_groups_rpc_groups_proto_rawDescOnce sync.Once
	file_service_groups_rpc_groups_proto_rawDescData []byte
)

func file_service_groups_rpc_groups_proto_rawDescGZIP() []byte {
	file_service_groups_rpc_groups_proto_rawDescOnce.Do(func() {
		file_service_groups_rpc_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_groups_rpc_groups_proto_rawDesc), len(file_service_groups_rpc_groups_proto_rawDesc)))
	})
	return file_service_groups_rpc_groups_proto_rawDescData
}

var file_service_groups_rpc_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_service_groups_rpc_groups_proto_goTypes = []any{
	(*Group)(nil),               // 0: groups.v1.Group
	(*GroupMember)(nil),         // 1: groups.v1.GroupMember
	(*CreateGroupRequest)(nil),  // 2: groups.v1.CreateGroupRequest
	(*ListGroupsRequest)(nil),   // 3: groups.v1.ListGroupsRequest
	(*GetGroupRequest)(nil),     // 4: groups.v1.GetGroupRequest
	(*UpdateGroupRequest)(nil),  // 5: groups.v1.UpdateGroupRequest
	(*AddMemberRequest)(nil),    // 6: groups.v1.AddMemberRequest
	(*JoinGroupRequest)(nil),    // 7: groups.v1.JoinGroupRequest
	(*LeaveGroupRequest)(nil),   // 8: groups.v1.LeaveGroupRequest
	(*KickMemberRequest)(nil),   // 9: groups.v1.KickMemberRequest
	(*ListMembersRequest)(nil),  // 10: groups.v1.ListMembersRequest
	(*GroupResponse)(nil),       // 11: groups.v1.GroupResponse
	(*ListGroupsResponse)(nil),  // 12: groups.v1.ListGroupsResponse
	(*MemberResponse)(nil),      // 13: groups.v1.MemberResponse
	(*ListMembersResponse)(nil), // 14: groups.v1.ListMembersResponse
	(*IsMemberRequest)(nil),     // 15: groups.v1.IsMemberRequest
	(*IsMemberResponse)(nil),    // 16: groups.v1.IsMemberResponse
}
var file_service_groups_rpc_groups_proto_depIdxs = []int32{
	0,  // 0: groups.v1.GroupResponse.group:type_name -> groups.v1.Group
	0,  // 1: groups.v1.ListGroupsResponse.groups:type_name -> groups.v1.Group
	1,  // 2: groups.v1.MemberResponse.member:type_name -> groups.v1.GroupMember
	1,  // 3: groups.v1.ListMembersResponse.members:type_name -> groups.v1.GroupMember
	2,  // 4: groups.v1.Groups.CreateGroup:input_type -> groups.v1.CreateGroupRequest
	3,  // 5: groups.v1.Groups.ListGroups:input_type -> groups.v1.ListGroupsRequest
	4,  // 6: groups.v1.Groups.GetGroup:input_type -> groups.v1.GetGroupRequest
	5,  // 7: groups.v1.Groups.UpdateGroup:input_type -> groups.v1.UpdateGroupRequest
	6,  // 8: groups.v1.Groups.AddMember:input_type -> groups.v1.AddMemberRequest
	7,  // 9: groups.v1.Groups.JoinGroup:input_type -> groups.v1.JoinGroupRequest
	8,  // 10: groups.v1.Groups.LeaveGroup:input_type -> groups.v1.LeaveGroupRequest
	9,  // 11: groups.v1.Groups.KickMember:input_type -> groups.v1.KickMemberRequest
	10, // 12: groups.v1.Groups.ListMembers:input_type -> groups.v1.ListMembersRequest
	15, // 13: groups.v1.Groups.IsMember:input_type -> groups.v1.IsMemberRequest
	11, // 14: groups.v1.Groups.CreateGroup:output_type -> groups.v1.GroupResponse
	12, // 15: groups.v1.Groups.ListGroups:output_type -> groups.v1.ListGroupsResponse
	11, // 16: groups.v1.Groups.GetGroup:output_type -> groups.v1.GroupResponse
	11, // 17: groups.v1.Groups.UpdateGroup:output_type -> groups.v1.GroupResponse
	13, // 18: groups.v1.Groups.AddMember:output_type -> groups.v1.MemberResponse
	13, // 19: groups.v1.Groups.JoinGroup:output_type -> groups.v1.MemberResponse
	13, // 20: groups.v1.Groups.LeaveGroup:output_type -> groups.v1.MemberResponse
	13, // 21: groups.v1.Groups.KickMember:output_type -> groups.v1.MemberResponse
	14, // 22: groups.v1.Groups.ListMembers:output_type -> groups.v1.ListMembersResponse
	16, // 23: groups.v1.Groups.IsMember:output_type -> groups.v1.IsMemberResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_service_groups_rpc_groups_proto_init() }
func file_service_groups_rpc_groups_proto_init() {
	if File_service_groups_rpc_groups_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_groups_rpc_groups_proto_rawDesc), len(file_service_groups_rpc_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_groups_rpc_groups_proto_goTypes,
		DependencyIndexes: file_service_groups_rpc_groups_proto_depIdxs,
		MessageInfos:      file_service_groups_rpc_groups_proto_msgTypes,
	}.Build()
	File_service_groups_rpc_groups_proto = out.File
	file_service_groups_rpc_groups_proto_goTypes = nil
	file_service_groups_rpc_groups_proto_depIdxs = nil
}
