// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: msg.proto

package msgclient

import (
	"context"

	"github.com/wujunhui99/agents_im/service/msg/rpc/msg"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AppendStreamMessageRequest         = msg.AppendStreamMessageRequest
	AppendStreamMessageResponse        = msg.AppendStreamMessageResponse
	ClearConversationMessagesRequest   = msg.ClearConversationMessagesRequest
	ClearConversationMessagesResponse  = msg.ClearConversationMessagesResponse
	ConversationAIHostingState         = msg.ConversationAIHostingState
	ConversationSeqState               = msg.ConversationSeqState
	DeleteMessagesRequest              = msg.DeleteMessagesRequest
	DeleteMessagesResponse             = msg.DeleteMessagesResponse
	GetConversationAIHostingRequest    = msg.GetConversationAIHostingRequest
	GetConversationsSeqStateRequest    = msg.GetConversationsSeqStateRequest
	GetConversationsSeqStateResponse   = msg.GetConversationsSeqStateResponse
	GetHasReadSeqsRequest              = msg.GetHasReadSeqsRequest
	GetHasReadSeqsResponse             = msg.GetHasReadSeqsResponse
	GetLastMessageByConvsRequest       = msg.GetLastMessageByConvsRequest
	GetLastMessageByConvsResponse      = msg.GetLastMessageByConvsResponse
	GetMaxSeqsRequest                  = msg.GetMaxSeqsRequest
	GetMaxSeqsResponse                 = msg.GetMaxSeqsResponse
	GetMessageRefRequest               = msg.GetMessageRefRequest
	GetMessageRefResponse              = msg.GetMessageRefResponse
	GetServerTimeRequest               = msg.GetServerTimeRequest
	GetServerTimeResponse              = msg.GetServerTimeResponse
	MarkConversationAsReadRequest      = msg.MarkConversationAsReadRequest
	MarkConversationAsReadResponse     = msg.MarkConversationAsReadResponse
	Message                            = msg.Message
	PullMessagesRequest                = msg.PullMessagesRequest
	PullMessagesResponse               = msg.PullMessagesResponse
	RevokeMessageRequest               = msg.RevokeMessageRequest
	RevokeMessageResponse              = msg.RevokeMessageResponse
	SendMessageRequest                 = msg.SendMessageRequest
	SendMessageResponse                = msg.SendMessageResponse
	UpdateConversationAIHostingRequest = msg.UpdateConversationAIHostingRequest

	Msg interface {
		// 写
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		AppendStreamMessage(ctx context.Context, in *AppendStreamMessageRequest, opts ...grpc.CallOption) (*AppendStreamMessageResponse, error)
		// 拉历史
		PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error)
		GetLastMessageByConvs(ctx context.Context, in *GetLastMessageByConvsRequest, opts ...grpc.CallOption) (*GetLastMessageByConvsResponse, error)
		// seq 同步
		GetConversationsSeqState(ctx context.Context, in *GetConversationsSeqStateRequest, opts ...grpc.CallOption) (*GetConversationsSeqStateResponse, error)
		GetMaxSeqs(ctx context.Context, in *GetMaxSeqsRequest, opts ...grpc.CallOption) (*GetMaxSeqsResponse, error)
		GetHasReadSeqs(ctx context.Context, in *GetHasReadSeqsRequest, opts ...grpc.CallOption) (*GetHasReadSeqsResponse, error)
		// 已读
		MarkConversationAsRead(ctx context.Context, in *MarkConversationAsReadRequest, opts ...grpc.CallOption) (*MarkConversationAsReadResponse, error)
		// 媒体下载授权（§4）
		GetMessageRef(ctx context.Context, in *GetMessageRefRequest, opts ...grpc.CallOption) (*GetMessageRefResponse, error)
		// 撤回 / 删除 / 清空（stub）
		RevokeMessage(ctx context.Context, in *RevokeMessageRequest, opts ...grpc.CallOption) (*RevokeMessageResponse, error)
		DeleteMessages(ctx context.Context, in *DeleteMessagesRequest, opts ...grpc.CallOption) (*DeleteMessagesResponse, error)
		ClearConversationMessages(ctx context.Context, in *ClearConversationMessagesRequest, opts ...grpc.CallOption) (*ClearConversationMessagesResponse, error)
		// 时间（stub）
		GetServerTime(ctx context.Context, in *GetServerTimeRequest, opts ...grpc.CallOption) (*GetServerTimeResponse, error)
		// AI 托管开关（keystone 例外：随 message-api 退役落到 msg-rpc，待 agent 域 rpc / 03 §9 B1 后迁出）
		GetConversationAIHosting(ctx context.Context, in *GetConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error)
		UpdateConversationAIHosting(ctx context.Context, in *UpdateConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error)
	}

	defaultMsg struct {
		cli zrpc.Client
	}
)

func NewMsg(cli zrpc.Client) Msg {
	return &defaultMsg{
		cli: cli,
	}
}

// 写
func (m *defaultMsg) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultMsg) AppendStreamMessage(ctx context.Context, in *AppendStreamMessageRequest, opts ...grpc.CallOption) (*AppendStreamMessageResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.AppendStreamMessage(ctx, in, opts...)
}

// 拉历史
func (m *defaultMsg) PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.PullMessages(ctx, in, opts...)
}

func (m *defaultMsg) GetLastMessageByConvs(ctx context.Context, in *GetLastMessageByConvsRequest, opts ...grpc.CallOption) (*GetLastMessageByConvsResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetLastMessageByConvs(ctx, in, opts...)
}

// seq 同步
func (m *defaultMsg) GetConversationsSeqState(ctx context.Context, in *GetConversationsSeqStateRequest, opts ...grpc.CallOption) (*GetConversationsSeqStateResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetConversationsSeqState(ctx, in, opts...)
}

func (m *defaultMsg) GetMaxSeqs(ctx context.Context, in *GetMaxSeqsRequest, opts ...grpc.CallOption) (*GetMaxSeqsResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetMaxSeqs(ctx, in, opts...)
}

func (m *defaultMsg) GetHasReadSeqs(ctx context.Context, in *GetHasReadSeqsRequest, opts ...grpc.CallOption) (*GetHasReadSeqsResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetHasReadSeqs(ctx, in, opts...)
}

// 已读
func (m *defaultMsg) MarkConversationAsRead(ctx context.Context, in *MarkConversationAsReadRequest, opts ...grpc.CallOption) (*MarkConversationAsReadResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.MarkConversationAsRead(ctx, in, opts...)
}

// 媒体下载授权（§4）
func (m *defaultMsg) GetMessageRef(ctx context.Context, in *GetMessageRefRequest, opts ...grpc.CallOption) (*GetMessageRefResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetMessageRef(ctx, in, opts...)
}

// 撤回 / 删除 / 清空（stub）
func (m *defaultMsg) RevokeMessage(ctx context.Context, in *RevokeMessageRequest, opts ...grpc.CallOption) (*RevokeMessageResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.RevokeMessage(ctx, in, opts...)
}

func (m *defaultMsg) DeleteMessages(ctx context.Context, in *DeleteMessagesRequest, opts ...grpc.CallOption) (*DeleteMessagesResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.DeleteMessages(ctx, in, opts...)
}

func (m *defaultMsg) ClearConversationMessages(ctx context.Context, in *ClearConversationMessagesRequest, opts ...grpc.CallOption) (*ClearConversationMessagesResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.ClearConversationMessages(ctx, in, opts...)
}

// 时间（stub）
func (m *defaultMsg) GetServerTime(ctx context.Context, in *GetServerTimeRequest, opts ...grpc.CallOption) (*GetServerTimeResponse, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetServerTime(ctx, in, opts...)
}

// AI 托管开关（keystone 例外：随 message-api 退役落到 msg-rpc，待 agent 域 rpc / 03 §9 B1 后迁出）
func (m *defaultMsg) GetConversationAIHosting(ctx context.Context, in *GetConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetConversationAIHosting(ctx, in, opts...)
}

func (m *defaultMsg) UpdateConversationAIHosting(ctx context.Context, in *UpdateConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.UpdateConversationAIHosting(ctx, in, opts...)
}
