// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Agent struct {
	AgentID     string `json:"agent_id"`
	IMUserID    string `json:"im_user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type AgentDefinitionData struct {
	Agent        Agent                 `json:"agent"`
	SystemPrompt AgentDefinitionPrompt `json:"system_prompt"`
	Tools        []AgentDefinitionTool `json:"tools"`
}

type AgentDefinitionPrompt struct {
	PromptID            string `json:"prompt_id"`
	Name                string `json:"name"`
	Description         string `json:"description"`
	Content             string `json:"content"`
	VariablesSchemaJSON string `json:"variables_schema_json"`
	Version             string `json:"version"`
	Status              string `json:"status"`
	CreatedBy           string `json:"created_by"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

type AgentDefinitionResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    AgentDefinitionData `json:"data"`
}

type AgentDefinitionTool struct {
	ToolID           string `json:"tool_id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	ToolType         string `json:"tool_type"`
	MCPServerID      string `json:"mcp_server_id,omitempty"`
	MCPToolName      string `json:"mcp_tool_name,omitempty"`
	LocalHandlerKey  string `json:"local_handler_key,omitempty"`
	BuiltinKey       string `json:"builtin_key,omitempty"`
	InputSchemaJSON  string `json:"input_schema_json"`
	OutputSchemaJSON string `json:"output_schema_json"`
	PermissionLevel  string `json:"permission_level"`
	Status           string `json:"status"`
	AdminConfigured  bool   `json:"admin_configured"`
}

type AgentPathReq struct {
	AgentID string `path:"agent_id"`
}

type AgentResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    Agent  `json:"data"`
}

type CreateAgentReq struct {
	IMUserID    string `json:"im_user_id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"`
}

type ListAgentsData struct {
	Agents []Agent `json:"agents"`
}

type ListAgentsReq struct {
	Status    string `form:"status,optional"`
	CreatedBy string `form:"created_by,optional"`
	Limit     int64  `form:"limit,optional"`
	Offset    int64  `form:"offset,optional"`
}

type ListAgentsResp struct {
	Code    string         `json:"code"`
	Message string         `json:"message"`
	Data    ListAgentsData `json:"data"`
}

type UpdateAgentDefinitionReq struct {
	AgentID      string   `path:"agent_id"`
	SystemPrompt string   `json:"system_prompt"`
	ToolNames    []string `json:"tool_names,optional"`
}

type UpdateAgentReq struct {
	AgentID     string `path:"agent_id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
}

type UpdateAgentStatusReq struct {
	AgentID string `path:"agent_id"`
	Status  string `json:"status"`
}
