Name: admin-api
Host: 0.0.0.0
Port: 8088

Auth:
  AccessSecret: ${JWT_ACCESS_SECRET}
  AccessExpire: 86400
StorageDriver: postgres
DataSource: ${DATABASE_URL}

Redis:
  Addr: ${REDIS_ADDR}
  Password: ${REDIS_PASSWORD}
  DB: ${REDIS_DB}
