Name: auth-api
Host: 0.0.0.0
Port: 8081

Auth:
  AccessSecret: ${JWT_ACCESS_SECRET}
  AccessExpire: 86400
StorageDriver: postgres
DataSource: ${DATABASE_URL}
MailRPC:
  Endpoints:
    - mail-rpc:9095
  Timeout: 5000
