Name: auth-rpc
ListenOn: 0.0.0.0:9091

TokenAuth:
  AccessSecret: ${JWT_ACCESS_SECRET}
  AccessExpire: 86400
StorageDriver: postgres
DataSource: ${DATABASE_URL}
MailRPC:
  Endpoints: mail-rpc:9095
  Timeout: 5000
