Name: friends-rpc
ListenOn: 0.0.0.0:9092

StorageDriver: postgres
DataSource: ${DATABASE_URL}
Tracing:
  Enabled: true
  Environment: ${AGENTS_IM_ENV}
  OTLPEndpoint: ${AGENTS_IM_OTLP_ENDPOINT}
  Protocol: ${AGENTS_IM_OTLP_PROTOCOL}
  SamplerRatio: 1.0
  JaegerBaseURL: ${AGENTS_IM_JAEGER_BASE_URL}
