// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/friends.proto

package friendspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Friendship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IsFriend      bool                   `protobuf:"varint,4,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friendship) Reset() {
	*x = Friendship{}
	mi := &file_proto_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friendship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friendship) ProtoMessage() {}

func (x *Friendship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friendship.ProtoReflect.Descriptor instead.
func (*Friendship) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{0}
}

func (x *Friendship) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friendship) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *Friendship) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Friendship) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

func (x *Friendship) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Friendship) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendRequest) Reset() {
	*x = AddFriendRequest{}
	mi := &file_proto_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequest) ProtoMessage() {}

func (x *AddFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequest.ProtoReflect.Descriptor instead.
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{1}
}

func (x *AddFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type AddFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *Friendship            `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendResponse) Reset() {
	*x = AddFriendResponse{}
	mi := &file_proto_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendResponse) ProtoMessage() {}

func (x *AddFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendResponse.ProtoReflect.Descriptor instead.
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{2}
}

func (x *AddFriendResponse) GetFriendship() *Friendship {
	if x != nil {
		return x.Friendship
	}
	return nil
}

func (x *AddFriendResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_proto_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type DeleteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *Friendship            `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResponse) Reset() {
	*x = DeleteFriendResponse{}
	mi := &file_proto_friends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResponse) ProtoMessage() {}

func (x *DeleteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFriendResponse) GetFriendship() *Friendship {
	if x != nil {
		return x.Friendship
	}
	return nil
}

func (x *DeleteFriendResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type AcceptFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequest) Reset() {
	*x = AcceptFriendRequest{}
	mi := &file_proto_friends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequest) ProtoMessage() {}

func (x *AcceptFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type AcceptFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *Friendship            `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendResponse) Reset() {
	*x = AcceptFriendResponse{}
	mi := &file_proto_friends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendResponse) ProtoMessage() {}

func (x *AcceptFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendResponse) GetFriendship() *Friendship {
	if x != nil {
		return x.Friendship
	}
	return nil
}

func (x *AcceptFriendResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RejectFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendRequest) Reset() {
	*x = RejectFriendRequest{}
	mi := &file_proto_friends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendRequest) ProtoMessage() {}

func (x *RejectFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendRequest.ProtoReflect.Descriptor instead.
func (*RejectFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{7}
}

func (x *RejectFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RejectFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type RejectFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *Friendship            `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	Rejected      bool                   `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendResponse) Reset() {
	*x = RejectFriendResponse{}
	mi := &file_proto_friends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendResponse) ProtoMessage() {}

func (x *RejectFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendResponse.ProtoReflect.Descriptor instead.
func (*RejectFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{8}
}

func (x *RejectFriendResponse) GetFriendship() *Friendship {
	if x != nil {
		return x.Friendship
	}
	return nil
}

func (x *RejectFriendResponse) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_proto_friends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{9}
}

func (x *ListFriendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friendship          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_proto_friends_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{10}
}

func (x *ListFriendsResponse) GetFriends() []*Friendship {
	if x != nil {
		return x.Friends
	}
	return nil
}

type ListFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestsRequest) Reset() {
	*x = ListFriendRequestsRequest{}
	mi := &file_proto_friends_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsRequest) ProtoMessage() {}

func (x *ListFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{11}
}

func (x *ListFriendRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListFriendRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incoming      []*Friendship          `protobuf:"bytes,1,rep,name=incoming,proto3" json:"incoming,omitempty"`
	Outgoing      []*Friendship          `protobuf:"bytes,2,rep,name=outgoing,proto3" json:"outgoing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestsResponse) Reset() {
	*x = ListFriendRequestsResponse{}
	mi := &file_proto_friends_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsResponse) ProtoMessage() {}

func (x *ListFriendRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendRequestsResponse) GetIncoming() []*Friendship {
	if x != nil {
		return x.Incoming
	}
	return nil
}

func (x *ListFriendRequestsResponse) GetOutgoing() []*Friendship {
	if x != nil {
		return x.Outgoing
	}
	return nil
}

type GetFriendshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendshipRequest) Reset() {
	*x = GetFriendshipRequest{}
	mi := &file_proto_friends_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipRequest) ProtoMessage() {}

func (x *GetFriendshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipRequest.ProtoReflect.Descriptor instead.
func (*GetFriendshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{13}
}

func (x *GetFriendshipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFriendshipRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type GetFriendshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *Friendship            `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendshipResponse) Reset() {
	*x = GetFriendshipResponse{}
	mi := &file_proto_friends_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipResponse) ProtoMessage() {}

func (x *GetFriendshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipResponse.ProtoReflect.Descriptor instead.
func (*GetFriendshipResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_proto_rawDescGZIP(), []int{14}
}

func (x *GetFriendshipResponse) GetFriendship() *Friendship {
	if x != nil {
		return x.Friendship
	}
	return nil
}

var File_proto_friends_proto protoreflect.FileDescriptor

const file_proto_friends_proto_rawDesc = "" +
	"\n" +
	"\x13proto/friends.proto\x12\n" +
	"friends.v1\"\xb5\x01\n" +
	"\n" +
	"Friendship\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tis_friend\x18\x04 \x01(\bR\bisFriend\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"H\n" +
	"\x10AddFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"e\n" +
	"\x11AddFriendResponse\x126\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x16.friends.v1.FriendshipR\n" +
	"friendship\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"K\n" +
	"\x13DeleteFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"h\n" +
	"\x14DeleteFriendResponse\x126\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x16.friends.v1.FriendshipR\n" +
	"friendship\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"K\n" +
	"\x13AcceptFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"j\n" +
	"\x14AcceptFriendResponse\x126\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x16.friends.v1.FriendshipR\n" +
	"friendship\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"K\n" +
	"\x13RejectFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"j\n" +
	"\x14RejectFriendResponse\x126\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x16.friends.v1.FriendshipR\n" +
	"friendship\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\bR\brejected\"-\n" +
	"\x12ListFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x13ListFriendsResponse\x120\n" +
	"\afriends\x18\x01 \x03(\v2\x16.friends.v1.FriendshipR\afriends\"4\n" +
	"\x19ListFriendRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x84\x01\n" +
	"\x1aListFriendRequestsResponse\x122\n" +
	"\bincoming\x18\x01 \x03(\v2\x16.friends.v1.FriendshipR\bincoming\x122\n" +
	"\boutgoing\x18\x02 \x03(\v2\x16.friends.v1.FriendshipR\boutgoing\"L\n" +
	"\x14GetFriendshipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"O\n" +
	"\x15GetFriendshipResponse\x126\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x16.friends.v1.FriendshipR\n" +
	"friendship2\xde\x04\n" +
	"\x0eFriendsService\x12H\n" +
	"\tAddFriend\x12\x1c.friends.v1.AddFriendRequest\x1a\x1d.friends.v1.AddFriendResponse\x12Q\n" +
	"\fAcceptFriend\x12\x1f.friends.v1.AcceptFriendRequest\x1a .friends.v1.AcceptFriendResponse\x12Q\n" +
	"\fRejectFriend\x12\x1f.friends.v1.RejectFriendRequest\x1a .friends.v1.RejectFriendResponse\x12Q\n" +
	"\fDeleteFriend\x12\x1f.friends.v1.DeleteFriendRequest\x1a .friends.v1.DeleteFriendResponse\x12N\n" +
	"\vListFriends\x12\x1e.friends.v1.ListFriendsRequest\x1a\x1f.friends.v1.ListFriendsResponse\x12c\n" +
	"\x12ListFriendRequests\x12%.friends.v1.ListFriendRequestsRequest\x1a&.friends.v1.ListFriendRequestsResponse\x12T\n" +
	"\rGetFriendship\x12 .friends.v1.GetFriendshipRequest\x1a!.friends.v1.GetFriendshipResponseB1Z/github.com/wujunhui99/agents_im/proto/friendspbb\x06proto3"

var (
	file_proto_friends_proto_rawDescOnce sync.Once
	file_proto_friends_proto_rawDescData []byte
)

func file_proto_friends_proto_rawDescGZIP() []byte {
	file_proto_friends_proto_rawDescOnce.Do(func() {
		file_proto_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friends_proto_rawDesc), len(file_proto_friends_proto_rawDesc)))
	})
	return file_proto_friends_proto_rawDescData
}

var file_proto_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_friends_proto_goTypes = []any{
	(*Friendship)(nil),                 // 0: friends.v1.Friendship
	(*AddFriendRequest)(nil),           // 1: friends.v1.AddFriendRequest
	(*AddFriendResponse)(nil),          // 2: friends.v1.AddFriendResponse
	(*DeleteFriendRequest)(nil),        // 3: friends.v1.DeleteFriendRequest
	(*DeleteFriendResponse)(nil),       // 4: friends.v1.DeleteFriendResponse
	(*AcceptFriendRequest)(nil),        // 5: friends.v1.AcceptFriendRequest
	(*AcceptFriendResponse)(nil),       // 6: friends.v1.AcceptFriendResponse
	(*RejectFriendRequest)(nil),        // 7: friends.v1.RejectFriendRequest
	(*RejectFriendResponse)(nil),       // 8: friends.v1.RejectFriendResponse
	(*ListFriendsRequest)(nil),         // 9: friends.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),        // 10: friends.v1.ListFriendsResponse
	(*ListFriendRequestsRequest)(nil),  // 11: friends.v1.ListFriendRequestsRequest
	(*ListFriendRequestsResponse)(nil), // 12: friends.v1.ListFriendRequestsResponse
	(*GetFriendshipRequest)(nil),       // 13: friends.v1.GetFriendshipRequest
	(*GetFriendshipResponse)(nil),      // 14: friends.v1.GetFriendshipResponse
}
var file_proto_friends_proto_depIdxs = []int32{
	0,  // 0: friends.v1.AddFriendResponse.friendship:type_name -> friends.v1.Friendship
	0,  // 1: friends.v1.DeleteFriendResponse.friendship:type_name -> friends.v1.Friendship
	0,  // 2: friends.v1.AcceptFriendResponse.friendship:type_name -> friends.v1.Friendship
	0,  // 3: friends.v1.RejectFriendResponse.friendship:type_name -> friends.v1.Friendship
	0,  // 4: friends.v1.ListFriendsResponse.friends:type_name -> friends.v1.Friendship
	0,  // 5: friends.v1.ListFriendRequestsResponse.incoming:type_name -> friends.v1.Friendship
	0,  // 6: friends.v1.ListFriendRequestsResponse.outgoing:type_name -> friends.v1.Friendship
	0,  // 7: friends.v1.GetFriendshipResponse.friendship:type_name -> friends.v1.Friendship
	1,  // 8: friends.v1.FriendsService.AddFriend:input_type -> friends.v1.AddFriendRequest
	5,  // 9: friends.v1.FriendsService.AcceptFriend:input_type -> friends.v1.AcceptFriendRequest
	7,  // 10: friends.v1.FriendsService.RejectFriend:input_type -> friends.v1.RejectFriendRequest
	3,  // 11: friends.v1.FriendsService.DeleteFriend:input_type -> friends.v1.DeleteFriendRequest
	9,  // 12: friends.v1.FriendsService.ListFriends:input_type -> friends.v1.ListFriendsRequest
	11, // 13: friends.v1.FriendsService.ListFriendRequests:input_type -> friends.v1.ListFriendRequestsRequest
	13, // 14: friends.v1.FriendsService.GetFriendship:input_type -> friends.v1.GetFriendshipRequest
	2,  // 15: friends.v1.FriendsService.AddFriend:output_type -> friends.v1.AddFriendResponse
	6,  // 16: friends.v1.FriendsService.AcceptFriend:output_type -> friends.v1.AcceptFriendResponse
	8,  // 17: friends.v1.FriendsService.RejectFriend:output_type -> friends.v1.RejectFriendResponse
	4,  // 18: friends.v1.FriendsService.DeleteFriend:output_type -> friends.v1.DeleteFriendResponse
	10, // 19: friends.v1.FriendsService.ListFriends:output_type -> friends.v1.ListFriendsResponse
	12, // 20: friends.v1.FriendsService.ListFriendRequests:output_type -> friends.v1.ListFriendRequestsResponse
	14, // 21: friends.v1.FriendsService.GetFriendship:output_type -> friends.v1.GetFriendshipResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_friends_proto_init() }
func file_proto_friends_proto_init() {
	if File_proto_friends_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friends_proto_rawDesc), len(file_proto_friends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friends_proto_goTypes,
		DependencyIndexes: file_proto_friends_proto_depIdxs,
		MessageInfos:      file_proto_friends_proto_msgTypes,
	}.Build()
	File_proto_friends_proto = out.File
	file_proto_friends_proto_goTypes = nil
	file_proto_friends_proto_depIdxs = nil
}
