// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accountsFieldNames          = builder.RawFieldNames(&Accounts{}, true)
	accountsRows                = strings.Join(accountsFieldNames, ",")
	accountsRowsExpectAutoSet   = strings.Join(stringx.Remove(accountsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	accountsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(accountsFieldNames, "account_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	accountsModel interface {
		Insert(ctx context.Context, data *Accounts) (sql.Result, error)
		FindOne(ctx context.Context, accountId string) (*Accounts, error)
		FindOneByEmailNormalized(ctx context.Context, emailNormalized string) (*Accounts, error)
		FindOneByIdentifier(ctx context.Context, identifier string) (*Accounts, error)
		Update(ctx context.Context, data *Accounts) error
		Delete(ctx context.Context, accountId string) error
	}

	defaultAccountsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Accounts struct {
		AccountId       string       `db:"account_id"`
		Identifier      string       `db:"identifier"`
		AccountType     int64        `db:"account_type"`
		CreatedAt       time.Time    `db:"created_at"`
		UpdatedAt       time.Time    `db:"updated_at"`
		EmailNormalized string       `db:"email_normalized"`
		EmailVerifiedAt sql.NullTime `db:"email_verified_at"`
	}
)

func newAccountsModel(conn sqlx.SqlConn) *defaultAccountsModel {
	return &defaultAccountsModel{
		conn:  conn,
		table: `"public"."accounts"`,
	}
}

func (m *defaultAccountsModel) Delete(ctx context.Context, accountId string) error {
	query := fmt.Sprintf("delete from %s where account_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, accountId)
	return err
}

func (m *defaultAccountsModel) FindOne(ctx context.Context, accountId string) (*Accounts, error) {
	query := fmt.Sprintf("select %s from %s where account_id = $1 limit 1", accountsRows, m.table)
	var resp Accounts
	err := m.conn.QueryRowCtx(ctx, &resp, query, accountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountsModel) FindOneByEmailNormalized(ctx context.Context, emailNormalized string) (*Accounts, error) {
	var resp Accounts
	query := fmt.Sprintf("select %s from %s where email_normalized = $1 limit 1", accountsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, emailNormalized)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountsModel) FindOneByIdentifier(ctx context.Context, identifier string) (*Accounts, error) {
	var resp Accounts
	query := fmt.Sprintf("select %s from %s where identifier = $1 limit 1", accountsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, identifier)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountsModel) Insert(ctx context.Context, data *Accounts) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, accountsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.Identifier, data.AccountType, data.EmailNormalized, data.EmailVerifiedAt)
	return ret, err
}

func (m *defaultAccountsModel) Update(ctx context.Context, newData *Accounts) error {
	query := fmt.Sprintf("update %s set %s where account_id = $1", m.table, accountsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AccountId, newData.Identifier, newData.AccountType, newData.EmailNormalized, newData.EmailVerifiedAt)
	return err
}

func (m *defaultAccountsModel) tableName() string {
	return m.table
}
