// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AdminAgentFileRead struct {
	FileReadID   string `json:"fileReadId"`
	RunID        string `json:"runId"`
	SkillID      string `json:"skillId,omitempty"`
	FileID       string `json:"fileId,omitempty"`
	Status       string `json:"status"`
	ByteCount    int64  `json:"byteCount,omitempty"`
	ErrorCode    string `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	StartedAt    string `json:"startedAt,omitempty"`
	FinishedAt   string `json:"finishedAt,omitempty"`
	CreatedAt    string `json:"createdAt,omitempty"`
}

type AdminAgentPythonExec struct {
	PythonExecID string `json:"pythonExecId"`
	RunID        string `json:"runId"`
	Status       string `json:"status"`
	ErrorCode    string `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	StartedAt    string `json:"startedAt,omitempty"`
	FinishedAt   string `json:"finishedAt,omitempty"`
	CreatedAt    string `json:"createdAt,omitempty"`
}

type AdminAgentToolCall struct {
	ToolCallID   string `json:"toolCallId"`
	RunID        string `json:"runId"`
	ToolName     string `json:"toolName"`
	Status       string `json:"status"`
	DurationMs   int64  `json:"durationMs,omitempty"`
	ErrorCode    string `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	StartedAt    string `json:"startedAt,omitempty"`
	FinishedAt   string `json:"finishedAt,omitempty"`
	CreatedAt    string `json:"createdAt,omitempty"`
}

type AdminConversation struct {
	ConversationID string        `json:"conversationId"`
	MaxSeq         int64         `json:"maxSeq"`
	HasReadSeq     int64         `json:"hasReadSeq,omitempty"`
	UnreadCount    int64         `json:"unreadCount,omitempty"`
	MaxSeqTime     int64         `json:"maxSeqTime,omitempty"`
	LastMessage    *AdminMessage `json:"lastMessage,omitempty"`
}

type AdminConversationMessagesData struct {
	ConversationID string         `json:"conversationId"`
	Messages       []AdminMessage `json:"messages"`
	IsEnd          bool           `json:"isEnd"`
	NextSeq        int64          `json:"nextSeq"`
}

type AdminConversationMessagesReq struct {
	ConversationID string `path:"conversation_id"`
	FromSeq        int64  `form:"fromSeq,optional"`
	ToSeq          int64  `form:"toSeq,optional"`
	Limit          int64  `form:"limit,optional"`
	Order          string `form:"order,optional"`
}

type AdminConversationMessagesResp struct {
	Code    string                        `json:"code"`
	Message string                        `json:"message"`
	Data    AdminConversationMessagesData `json:"data"`
}

type AdminDashboardData struct {
	Totals              AdminDashboardTotals `json:"totals"`
	RecentTraces        []AdminLLMTrace      `json:"recentTraces"`
	RecentConversations []AdminConversation  `json:"recentConversations"`
}

type AdminDashboardReq struct {
	Limit int64 `form:"limit,optional"`
}

type AdminDashboardResp struct {
	Code    string             `json:"code"`
	Message string             `json:"message"`
	Data    AdminDashboardData `json:"data"`
}

type AdminDashboardTotals struct {
	Users         int64 `json:"users"`
	Conversations int64 `json:"conversations"`
	Messages      int64 `json:"messages"`
	AIRuns        int64 `json:"aiRuns"`
	FailedAIRuns  int64 `json:"failedAiRuns"`
}

type AdminFeedback struct {
	FeedbackID string                 `json:"feedbackId"`
	UserID     string                 `json:"userId"`
	Category   string                 `json:"category"`
	Status     string                 `json:"status"`
	Title      string                 `json:"title"`
	Content    string                 `json:"content"`
	Contact    string                 `json:"contact,omitempty"`
	PageURL    string                 `json:"pageUrl,omitempty"`
	UserAgent  string                 `json:"userAgent,omitempty"`
	ClientMeta map[string]interface{} `json:"clientMeta,omitempty"`
	AdminNote  string                 `json:"adminNote,omitempty"`
	CreatedAt  string                 `json:"createdAt"`
	UpdatedAt  string                 `json:"updatedAt"`
}

type AdminFeedbackDetailData struct {
	Feedback AdminFeedback `json:"feedback"`
}

type AdminFeedbackDetailResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    AdminFeedbackDetailData `json:"data"`
}

type AdminFeedbackListData struct {
	Items []AdminFeedback `json:"items"`
}

type AdminFeedbackListReq struct {
	Status string `form:"status,optional"`
	Limit  int64  `form:"limit,optional"`
	Offset int64  `form:"offset,optional"`
}

type AdminFeedbackListResp struct {
	Code    string                `json:"code"`
	Message string                `json:"message"`
	Data    AdminFeedbackListData `json:"data"`
}

type AdminFeedbackReq struct {
	FeedbackID string `path:"feedback_id"`
}

type AdminFeedbackUpdateReq struct {
	FeedbackID string `path:"feedback_id"`
	Status     string `json:"status"`
	AdminNote  string `json:"adminNote,optional"`
}

type AdminFriend struct {
	UserID    string     `json:"userId"`
	FriendID  string     `json:"friendId"`
	Status    string     `json:"status"`
	IsFriend  bool       `json:"isFriend"`
	Friend    *AdminUser `json:"friend,omitempty"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
}

type AdminLLMTrace struct {
	TraceID           string `json:"traceId"`
	TraceURL          string `json:"traceUrl,omitempty"`
	RunID             string `json:"runId"`
	AgentID           string `json:"agentId"`
	ConversationID    string `json:"conversationId,omitempty"`
	TriggerMessageID  string `json:"triggerMessageId,omitempty"`
	ResponseMessageID string `json:"responseMessageId,omitempty"`
	RequestingUserID  string `json:"requestingUserId,omitempty"`
	Status            string `json:"status"`
	Provider          string `json:"provider,omitempty"`
	Model             string `json:"model,omitempty"`
	PromptHash        string `json:"promptHash,omitempty"`
	PromptVersion     string `json:"promptVersion,omitempty"`
	LatencyMs         int64  `json:"latencyMs,omitempty"`
	TotalTokens       int64  `json:"totalTokens,omitempty"`
	ErrorCode         string `json:"errorCode,omitempty"`
	ErrorMessage      string `json:"errorMessage,omitempty"`
	StartedAt         string `json:"startedAt,omitempty"`
	FinishedAt        string `json:"finishedAt,omitempty"`
	CreatedAt         string `json:"createdAt,omitempty"`
}

type AdminLLMTraceDetailData struct {
	Trace       AdminLLMTrace          `json:"trace"`
	ToolCalls   []AdminAgentToolCall   `json:"toolCalls"`
	FileReads   []AdminAgentFileRead   `json:"fileReads"`
	PythonExecs []AdminAgentPythonExec `json:"pythonExecs"`
}

type AdminLLMTraceDetailResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    AdminLLMTraceDetailData `json:"data"`
}

type AdminLLMTraceListData struct {
	Traces []AdminLLMTrace `json:"traces"`
}

type AdminLLMTraceListReq struct {
	Status string `form:"status,optional"`
	Limit  int64  `form:"limit,optional"`
	Offset int64  `form:"offset,optional"`
}

type AdminLLMTraceListResp struct {
	Code    string                `json:"code"`
	Message string                `json:"message"`
	Data    AdminLLMTraceListData `json:"data"`
}

type AdminLLMTraceReq struct {
	TraceID string `path:"trace_id"`
}

type AdminMessage struct {
	ServerMsgID           string `json:"serverMsgId"`
	ClientMsgID           string `json:"clientMsgId"`
	ConversationID        string `json:"conversationId"`
	Seq                   int64  `json:"seq"`
	SenderID              string `json:"senderId"`
	ReceiverID            string `json:"receiverId,omitempty"`
	GroupID               string `json:"groupId,omitempty"`
	ChatType              string `json:"chatType"`
	ContentType           string `json:"contentType"`
	Content               string `json:"content"`
	MessageOrigin         string `json:"messageOrigin"`
	AgentAccountID        string `json:"agentAccountId,omitempty"`
	TriggerServerMsgID    string `json:"triggerServerMsgId,omitempty"`
	AgentRunID            string `json:"agentRunId,omitempty"`
	AllowRecursiveTrigger bool   `json:"allowRecursiveTrigger,omitempty"`
	SendTime              int64  `json:"sendTime"`
	CreatedAt             int64  `json:"createdAt"`
}

type AdminReplayAgentMessageData struct {
	ConversationID string       `json:"conversationId"`
	ServerMsgID    string       `json:"serverMsgId"`
	Triggered      bool         `json:"triggered"`
	Skipped        bool         `json:"skipped"`
	Reason         string       `json:"reason,omitempty"`
	Message        AdminMessage `json:"message"`
}

type AdminReplayAgentMessageReq struct {
	ConversationID string `path:"conversation_id"`
	ServerMsgID    string `path:"server_msg_id"`
}

type AdminReplayAgentMessageResp struct {
	Code    string                      `json:"code"`
	Message string                      `json:"message"`
	Data    AdminReplayAgentMessageData `json:"data"`
}

type AdminTaskReport struct {
	TaskID                  string   `json:"taskId"`
	Agent                   string   `json:"agent"`
	CodexSessionID          string   `json:"codexSessionId,omitempty"`
	IssueNumber             int64    `json:"issueNumber,omitempty"`
	IssueURL                string   `json:"issueUrl,omitempty"`
	Repo                    string   `json:"repo"`
	Branch                  string   `json:"branch,omitempty"`
	Worktree                string   `json:"worktree,omitempty"`
	Commit                  string   `json:"commit,omitempty"`
	Outcome                 string   `json:"outcome"`
	StartedAt               string   `json:"startedAt,omitempty"`
	EndedAt                 string   `json:"endedAt,omitempty"`
	DurationSeconds         int64    `json:"durationSeconds,omitempty"`
	TokensUsed              int64    `json:"tokensUsed,omitempty"`
	PRURL                   string   `json:"prUrl,omitempty"`
	Evidence                []string `json:"evidence"`
	Blockers                []string `json:"blockers"`
	MajorTimeSinks          []string `json:"majorTimeSinks"`
	WouldMorePermissionHelp string   `json:"wouldMorePermissionHelp,omitempty"`
	CandidatePermissions    []string `json:"candidatePermissions"`
	PermissionReason        string   `json:"permissionReason,omitempty"`
	PitfallsOrLessons       []string `json:"pitfallsOrLessons"`
	Notes                   string   `json:"notes,omitempty"`
	RecordedAt              string   `json:"recordedAt"`
}

type AdminTaskReportDetailData struct {
	Report AdminTaskReport `json:"report"`
}

type AdminTaskReportDetailResp struct {
	Code    string                    `json:"code"`
	Message string                    `json:"message"`
	Data    AdminTaskReportDetailData `json:"data"`
}

type AdminTaskReportIngestReq struct {
	TaskID             string                            `json:"task_id"`
	Agent              string                            `json:"agent"`
	CodexSessionID     string                            `json:"codex_session_id,optional"`
	Issue              AdminTaskReportIssue              `json:"issue,optional"`
	Repo               string                            `json:"repo"`
	Branch             string                            `json:"branch,optional"`
	Worktree           string                            `json:"worktree,optional"`
	Commit             string                            `json:"commit,optional"`
	Outcome            string                            `json:"outcome"`
	StartedAt          string                            `json:"started_at,optional"`
	EndedAt            string                            `json:"ended_at,optional"`
	DurationSeconds    int64                             `json:"duration_seconds,optional"`
	TokensUsed         int64                             `json:"tokens_used,optional"`
	PRURL              string                            `json:"pr_url,optional"`
	Evidence           []string                          `json:"evidence,optional"`
	Blockers           []string                          `json:"blockers,optional"`
	MajorTimeSinks     []string                          `json:"major_time_sinks,optional"`
	PermissionAnalysis AdminTaskReportPermissionAnalysis `json:"permission_analysis,optional"`
	PitfallsOrLessons  []string                          `json:"pitfalls_or_lessons,optional"`
	Notes              string                            `json:"notes,optional"`
	RecordedAt         string                            `json:"recorded_at,optional"`
}

type AdminTaskReportIssue struct {
	Number int64  `json:"number,optional"`
	URL    string `json:"url,optional"`
}

type AdminTaskReportListData struct {
	Items []AdminTaskReport `json:"items"`
}

type AdminTaskReportListReq struct {
	Outcome string `form:"outcome,optional"`
	Limit   int64  `form:"limit,optional"`
	Offset  int64  `form:"offset,optional"`
}

type AdminTaskReportListResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    AdminTaskReportListData `json:"data"`
}

type AdminTaskReportPermissionAnalysis struct {
	WouldMorePermissionHelp string   `json:"would_more_permission_help,optional"`
	CandidatePermissions    []string `json:"candidate_permissions,optional"`
	Reason                  string   `json:"reason,optional"`
}

type AdminTestAccountCreateReq struct {
	Identifier  string `json:"identifier"`
	DisplayName string `json:"displayName,optional"`
	Password    string `json:"password,optional"`
}

type AdminTestAccountCreateResp struct {
	Code    string               `json:"code"`
	Message string               `json:"message"`
	Data    AdminTestAccountData `json:"data"`
}

type AdminTestAccountData struct {
	User           AdminUser `json:"user"`
	Password       string    `json:"password"`
	AlreadyExisted bool      `json:"alreadyExisted"`
}

type AdminUser struct {
	UserID        string `json:"userId"`
	AccountID     string `json:"accountId,omitempty"`
	Identifier    string `json:"identifier"`
	DisplayName   string `json:"displayName"`
	Name          string `json:"name"`
	Gender        string `json:"gender"`
	BirthDate     string `json:"birthDate"`
	Region        string `json:"region"`
	AccountType   string `json:"accountType"`
	AvatarMediaID string `json:"avatarMediaId,omitempty"`
	AvatarURL     string `json:"avatarUrl,omitempty"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type AdminUserConversationsData struct {
	Conversations []AdminConversation `json:"conversations"`
}

type AdminUserConversationsResp struct {
	Code    string                     `json:"code"`
	Message string                     `json:"message"`
	Data    AdminUserConversationsData `json:"data"`
}

type AdminUserDetailData struct {
	User AdminUser `json:"user"`
}

type AdminUserDetailResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    AdminUserDetailData `json:"data"`
}

type AdminUserFriendsData struct {
	Friends []AdminFriend `json:"friends"`
}

type AdminUserFriendsResp struct {
	Code    string               `json:"code"`
	Message string               `json:"message"`
	Data    AdminUserFriendsData `json:"data"`
}

type AdminUserReq struct {
	AccountID string `path:"account_id"`
}

type AdminUserSearchData struct {
	Users []AdminUser `json:"users"`
}

type AdminUserSearchReq struct {
	Query string `form:"query,optional"`
	Limit int64  `form:"limit,optional"`
}

type AdminUserSearchResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    AdminUserSearchData `json:"data"`
}
