// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: media.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/service/media/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/media/rpc/internal/svc"
	"github.com/wujunhui99/agents_im/service/media/rpc/media"
)

type MediaServer struct {
	svcCtx *svc.ServiceContext
	media.UnimplementedMediaServer
}

func NewMediaServer(svcCtx *svc.ServiceContext) *MediaServer {
	return &MediaServer{
		svcCtx: svcCtx,
	}
}

func (s *MediaServer) CreateUploadIntent(ctx context.Context, in *media.CreateUploadIntentRequest) (*media.CreateUploadIntentResponse, error) {
	l := logic.NewCreateUploadIntentLogic(ctx, s.svcCtx)
	return l.CreateUploadIntent(in)
}

func (s *MediaServer) CompleteUpload(ctx context.Context, in *media.CompleteUploadRequest) (*media.CompleteUploadResponse, error) {
	l := logic.NewCompleteUploadLogic(ctx, s.svcCtx)
	return l.CompleteUpload(in)
}

func (s *MediaServer) GetDownloadURL(ctx context.Context, in *media.GetDownloadURLRequest) (*media.GetDownloadURLResponse, error) {
	l := logic.NewGetDownloadURLLogic(ctx, s.svcCtx)
	return l.GetDownloadURL(in)
}

func (s *MediaServer) GetAvatarDisplayURL(ctx context.Context, in *media.GetAvatarDisplayURLRequest) (*media.GetDownloadURLResponse, error) {
	l := logic.NewGetAvatarDisplayURLLogic(ctx, s.svcCtx)
	return l.GetAvatarDisplayURL(in)
}
