// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messagesFieldNames          = builder.RawFieldNames(&Messages{}, true)
	messagesRows                = strings.Join(messagesFieldNames, ",")
	messagesRowsExpectAutoSet   = strings.Join(stringx.Remove(messagesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	messagesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(messagesFieldNames, "message_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	messagesModel interface {
		Insert(ctx context.Context, data *Messages) (sql.Result, error)
		FindOne(ctx context.Context, messageId int64) (*Messages, error)
		FindOneByConversationIdSeq(ctx context.Context, conversationId string, seq int64) (*Messages, error)
		FindOneBySenderAccountIdClientMsgId(ctx context.Context, senderAccountId string, clientMsgId string) (*Messages, error)
		Update(ctx context.Context, data *Messages) error
		Delete(ctx context.Context, messageId int64) error
	}

	defaultMessagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Messages struct {
		MessageId             int64        `db:"message_id"`
		ClientMsgId           string       `db:"client_msg_id"`
		SenderAccountId       string       `db:"sender_account_id"`
		ConversationId        string       `db:"conversation_id"`
		Seq                   int64        `db:"seq"`
		ConversationType      int64        `db:"conversation_type"`
		ReceiverAccountId     string       `db:"receiver_account_id"`
		GroupId               string       `db:"group_id"`
		ContentType           int64        `db:"content_type"`
		Content               string       `db:"content"`
		PayloadHash           string       `db:"payload_hash"`
		ClientSendTime        sql.NullTime `db:"client_send_time"`
		ServerReceivedAt      time.Time    `db:"server_received_at"`
		MessageState          int64        `db:"message_state"`
		CreatedAt             time.Time    `db:"created_at"`
		UpdatedAt             time.Time    `db:"updated_at"`
		MessageOrigin         int64        `db:"message_origin"`
		AgentAccountId        string       `db:"agent_account_id"`
		TriggerMessageId      string       `db:"trigger_message_id"`
		AgentRunId            string       `db:"agent_run_id"`
		AllowRecursiveTrigger bool         `db:"allow_recursive_trigger"`
	}
)

func newMessagesModel(conn sqlx.SqlConn) *defaultMessagesModel {
	return &defaultMessagesModel{
		conn:  conn,
		table: `"public"."messages"`,
	}
}

func (m *defaultMessagesModel) Delete(ctx context.Context, messageId int64) error {
	query := fmt.Sprintf("delete from %s where message_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, messageId)
	return err
}

func (m *defaultMessagesModel) FindOne(ctx context.Context, messageId int64) (*Messages, error) {
	query := fmt.Sprintf("select %s from %s where message_id = $1 limit 1", messagesRows, m.table)
	var resp Messages
	err := m.conn.QueryRowCtx(ctx, &resp, query, messageId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) FindOneByConversationIdSeq(ctx context.Context, conversationId string, seq int64) (*Messages, error) {
	var resp Messages
	query := fmt.Sprintf("select %s from %s where conversation_id = $1 and seq = $2 limit 1", messagesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, conversationId, seq)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) FindOneBySenderAccountIdClientMsgId(ctx context.Context, senderAccountId string, clientMsgId string) (*Messages, error) {
	var resp Messages
	query := fmt.Sprintf("select %s from %s where sender_account_id = $1 and client_msg_id = $2 limit 1", messagesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, senderAccountId, clientMsgId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) Insert(ctx context.Context, data *Messages) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)", m.table, messagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MessageId, data.ClientMsgId, data.SenderAccountId, data.ConversationId, data.Seq, data.ConversationType, data.ReceiverAccountId, data.GroupId, data.ContentType, data.Content, data.PayloadHash, data.ClientSendTime, data.ServerReceivedAt, data.MessageState, data.MessageOrigin, data.AgentAccountId, data.TriggerMessageId, data.AgentRunId, data.AllowRecursiveTrigger)
	return ret, err
}

func (m *defaultMessagesModel) Update(ctx context.Context, newData *Messages) error {
	query := fmt.Sprintf("update %s set %s where message_id = $1", m.table, messagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MessageId, newData.ClientMsgId, newData.SenderAccountId, newData.ConversationId, newData.Seq, newData.ConversationType, newData.ReceiverAccountId, newData.GroupId, newData.ContentType, newData.Content, newData.PayloadHash, newData.ClientSendTime, newData.ServerReceivedAt, newData.MessageState, newData.MessageOrigin, newData.AgentAccountId, newData.TriggerMessageId, newData.AgentRunId, newData.AllowRecursiveTrigger)
	return err
}

func (m *defaultMessagesModel) tableName() string {
	return m.table
}
