// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: groups.proto

package groupsservice

import (
	"context"

	"github.com/wujunhui99/agents_im/proto/groupspb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberRequest    = groupspb.AddMemberRequest
	CreateGroupRequest  = groupspb.CreateGroupRequest
	GetGroupRequest     = groupspb.GetGroupRequest
	Group               = groupspb.Group
	GroupMember         = groupspb.GroupMember
	GroupResponse       = groupspb.GroupResponse
	JoinGroupRequest    = groupspb.JoinGroupRequest
	LeaveGroupRequest   = groupspb.LeaveGroupRequest
	ListMembersRequest  = groupspb.ListMembersRequest
	ListMembersResponse = groupspb.ListMembersResponse
	MemberResponse      = groupspb.MemberResponse

	GroupsService interface {
		CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
		GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
		AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberResponse, error)
		JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*MemberResponse, error)
		LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*MemberResponse, error)
		ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	}

	defaultGroupsService struct {
		cli zrpc.Client
	}
)

func NewGroupsService(cli zrpc.Client) GroupsService {
	return &defaultGroupsService{
		cli: cli,
	}
}

func (m *defaultGroupsService) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	client := groupspb.NewGroupsServiceClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroupsService) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	client := groupspb.NewGroupsServiceClient(m.cli.Conn())
	return client.GetGroup(ctx, in, opts...)
}

func (m *defaultGroupsService) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberResponse, error) {
	client := groupspb.NewGroupsServiceClient(m.cli.Conn())
	return client.AddMember(ctx, in, opts...)
}

func (m *defaultGroupsService) JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*MemberResponse, error) {
	client := groupspb.NewGroupsServiceClient(m.cli.Conn())
	return client.JoinGroup(ctx, in, opts...)
}

func (m *defaultGroupsService) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*MemberResponse, error) {
	client := groupspb.NewGroupsServiceClient(m.cli.Conn())
	return client.LeaveGroup(ctx, in, opts...)
}

func (m *defaultGroupsService) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	client := groupspb.NewGroupsServiceClient(m.cli.Conn())
	return client.ListMembers(ctx, in, opts...)
}
