#!/usr/bin/env bash
# Static verification orchestrator.
#
# Preflight (required files + shell syntax) then runs the themed gates under
# scripts/verify/. Each gate is also runnable standalone:
#   scripts/verify/verify-security-static.sh    secrets / key material / auth-leak
#   scripts/verify/verify-gozero-boundaries.sh  go-zero layering boundaries
#   scripts/verify/verify-contract-markers.sh   API/proto/schema/code contract surface
#   scripts/verify/verify-deploy-static.sh      deploy / CI / middleware / k8s config
#   scripts/verify/verify-frontend-static.sh    web/ frontend gates
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/verify/lib.sh"
cd "$(git rev-parse --show-toplevel)"

required_files=(
  "api/message.api"
  "api/media.api"
  ".drone.yml"
  ".github/markdown-link-check.json"
  "service/user/rpc/user.proto"
  "service/user/api/user.api"
  "service/auth/rpc/auth.proto"
  "service/auth/api/auth.api"
  "service/friends/rpc/friends.proto"
  "service/friends/api/friends.api"
  "service/groups/rpc/groups.proto"
  "service/groups/api/groups.api"
  "service/agent/api/agent.api"
  "internal/rpcgen/message/message.proto"
  "service/third/rpc/mail.proto"
  "service/user/rpc/user/user.pb.go"
  "service/user/rpc/user/user_grpc.pb.go"
  "service/auth/rpc/auth/auth.pb.go"
  "service/auth/rpc/auth/auth_grpc.pb.go"
  "service/friends/rpc/friends/friends.pb.go"
  "service/friends/rpc/friends/friends_grpc.pb.go"
  "service/groups/rpc/groups/groups.pb.go"
  "service/groups/rpc/groups/groups_grpc.pb.go"
  "internal/rpcgen/message/messagepb/message.pb.go"
  "internal/rpcgen/message/messagepb/message_grpc.pb.go"
  "service/third/rpc/mail/mail.pb.go"
  "service/third/rpc/mail/mail_grpc.pb.go"
  "service/user/rpc/user.go"
  "service/user/rpc/internal/server/userserver.go"
  "service/auth/rpc/auth.go"
  "service/auth/rpc/internal/server/authserver.go"
  "service/friends/rpc/friends.go"
  "service/friends/rpc/internal/server/friendsserver.go"
  "service/admin/rpc/admin.go"
  "service/admin/rpc/internal/server/adminserver.go"
  "service/admin/rpc/admin/admin.pb.go"
  "service/admin/rpc/admin/admin_grpc.pb.go"
  "service/groups/rpc/groups.go"
  "service/groups/rpc/internal/server/groupsserver.go"
  "service/user/api/user.go"
  "service/auth/api/auth.go"
  "service/friends/api/friends.go"
  "service/groups/api/groups.go"
  "service/agent/api/agent.go"
  "service/user/api/internal/config/config.go"
  "service/user/api/internal/handler/routes.go"
  "service/user/api/internal/svc/service_context.go"
  "service/user/api/internal/types/types.go"
  "service/auth/api/internal/config/config.go"
  "service/auth/api/internal/handler/routes.go"
  "service/auth/api/internal/svc/service_context.go"
  "service/auth/api/internal/types/types.go"
  "service/auth/api/internal/logic/auth/request_registration_email_code_logic.go"
  "service/auth/api/internal/logic/auth/register_logic.go"
  "service/auth/api/internal/logic/auth/login_logic.go"
  "service/auth/api/internal/logic/auth/validate_token_logic.go"
  "service/auth/api/internal/logic/auth/convert.go"
  "service/user/api/internal/logic/user/create_user_logic.go"
  "service/user/api/internal/logic/user/create_account_logic.go"
  "service/user/api/internal/logic/user/exists_user_logic.go"
  "service/user/api/internal/logic/user/exists_account_logic.go"
  "service/user/api/internal/logic/user/get_me_logic.go"
  "service/user/api/internal/logic/user/get_user_by_identifier_logic.go"
  "service/user/api/internal/logic/user/get_account_by_identifier_logic.go"
  "service/user/api/internal/logic/user/update_me_logic.go"
  "service/user/api/internal/logic/user/update_me_avatar_logic.go"
  "service/user/api/internal/logic/user/convert.go"
  "service/friends/api/internal/config/config.go"
  "service/friends/api/internal/handler/routes.go"
  "service/friends/api/internal/svc/service_context.go"
  "service/friends/api/internal/types/types.go"
  "service/friends/api/internal/logic/friends/add_friend_logic.go"
  "service/friends/api/internal/logic/friends/delete_friend_logic.go"
  "service/friends/api/internal/logic/friends/get_friendship_logic.go"
  "service/friends/api/internal/logic/friends/list_friends_logic.go"
  "service/friends/api/internal/logic/friends/list_friend_requests_logic.go"
  "service/friends/api/internal/logic/friends/accept_friend_request_logic.go"
  "service/friends/api/internal/logic/friends/reject_friend_request_logic.go"
  "service/friends/api/internal/logic/friends/convert.go"
  "service/groups/api/internal/config/config.go"
  "service/groups/api/internal/handler/routes.go"
  "service/groups/api/internal/svc/service_context.go"
  "service/groups/api/internal/types/types.go"
  "service/groups/api/internal/logic/groups/create_group_logic.go"
  "service/groups/api/internal/logic/groups/list_groups_logic.go"
  "service/groups/api/internal/logic/groups/get_group_logic.go"
  "service/groups/api/internal/logic/groups/update_group_logic.go"
  "service/groups/api/internal/logic/groups/add_member_logic.go"
  "service/groups/api/internal/logic/groups/leave_group_logic.go"
  "service/groups/api/internal/logic/groups/kick_member_logic.go"
  "service/groups/api/internal/logic/groups/list_members_logic.go"
  "service/groups/api/internal/logic/groups/convert.go"
  "service/agent/api/internal/config/config.go"
  "service/agent/api/internal/handler/routes.go"
  "service/agent/api/internal/svc/service_context.go"
  "service/agent/api/internal/types/types.go"
  "service/agent/api/internal/logic/agent/create_agent_logic.go"
  "service/agent/api/internal/logic/agent/get_agent_logic.go"
  "service/agent/api/internal/logic/agent/list_agents_logic.go"
  "service/agent/api/internal/logic/agent/update_agent_logic.go"
  "service/agent/api/internal/logic/agent/update_agent_status_logic.go"
  "service/agent/api/internal/logic/agent/delete_agent_logic.go"
  "service/agent/api/internal/logic/agent/get_agent_definition_logic.go"
  "service/agent/api/internal/logic/agent/update_agent_definition_logic.go"
  "service/agent/api/internal/logic/agent/convert.go"
  "internal/rpcgen/message/message.go"
  "internal/rpcgen/message/internal/server/message_service_server.go"
  "service/third/rpc/third.go"
  "service/third/rpc/internal/server/mailserver.go"
  "service/gateway-ws/main.go"
  "service/message-api/main.go"
  "service/message-transfer/main.go"
  "etc/gateway-ws.yaml"
  "etc/message-transfer.yaml"
  "etc/message-rpc.yaml"
  "etc/third-rpc.yaml"
  "service/third/rpc/internal/provider/provider.go"
  "service/third/rpc/internal/provider/config.go"
  "service/third/rpc/internal/provider/tencent_ses.go"
  "internal/logic/userlogic.go"
  "internal/logic/groupslogic.go"
  "internal/logic/messagelogic.go"
  "internal/logic/message_media_test.go"
  "internal/logic/message/send_message_logic.go"
  "internal/logic/message/pull_messages_logic.go"
  "internal/logic/message/get_conversation_seqs_logic.go"
  "internal/logic/message/mark_conversation_as_read_logic.go"
  "internal/logic/message/get_conversation_a_i_hosting_logic.go"
  "internal/logic/message/update_conversation_a_i_hosting_logic.go"
  "internal/logic/message/convert.go"
  "pkg/objectstorage/store.go"
  "pkg/objectstorage/minio.go"
  "pkg/objectstorage/memory.go"
  "internal/repository/memory.go"
  "internal/repository/postgres_common.go"
  "internal/repository/postgres_user_friends.go"
  "internal/repository/groups_memory.go"
  "internal/repository/groups_repository.go"
  "internal/repository/postgres_groups.go"
  "internal/repository/message_memory.go"
  "internal/repository/message_repository.go"
  "internal/repository/media_repository.go"
  "internal/repository/media_memory.go"
  "internal/repository/postgres_media.go"
  "internal/repository/message_outbox_repository.go"
  "internal/repository/delivery_attempt_repository.go"
  "internal/repository/postgres_message.go"
  "internal/repository/postgres_outbox.go"
  "internal/handler/health_handler.go"
  "internal/handler/gozero_routes.go"
  "internal/handler/message/get_conversation_a_i_hosting_handler.go"
  "internal/handler/message/update_conversation_a_i_hosting_handler.go"
  "internal/servicecontext/common/auth.go"
  "internal/servicecontext/message/service_context.go"
  "internal/servicecontext/gateway/service_context.go"
  "pkg/health/health.go"
  "pkg/health/health_test.go"
  "pkg/observability/metrics.go"
  "pkg/observability/metrics_test.go"
  "pkg/observability/trace.go"
  "pkg/observability/trace_test.go"
  "pkg/llmobs/types.go"
  "pkg/llmobs/sink.go"
  "pkg/llmobs/sink_test.go"
  "pkg/llmobs/sanitize.go"
  "pkg/llmobs/eino.go"
  "internal/agenteval/eval.go"
  "internal/agenteval/python_go_test.go"
  "internal/auth/logic/authlogic.go"
  "internal/auth/repository/memory.go"
  "internal/auth/repository/postgres.go"
  "internal/auth/useradapter/user_client.go"
  "pkg/ctxuser/user.go"
  "service/user/rpc/user.go"
  "service/auth/rpc/auth.go"
  "service/groups/rpc/groups.go"
  "internal/rpcgen/message/message.go"
  "internal/gateway/contract.go"
  "internal/transfer/event.go"
  "internal/transfer/interfaces.go"
  "internal/transfer/idempotency.go"
  "internal/transfer/delivery_attempt_recorder.go"
  "internal/transfer/memory.go"
  "internal/transfer/worker.go"
  "internal/transfer/worker_test.go"
  "pkg/presence/store.go"
  "pkg/presence/memory.go"
  "pkg/presence/redis.go"
  "pkg/presence/memory_test.go"
  "pkg/presence/redis_integration_test.go"
  "internal/gateway/ws/connection_manager.go"
  "internal/gateway/ws/server.go"
  "pkg/messaging/event.go"
  "pkg/messaging/event_test.go"
  "internal/gateway/delivery/delivery.go"
  "internal/gateway/ws/delivery.go"
  "internal/transfer/gateway/dispatcher.go"
  "internal/transfer/gateway/dispatcher_test.go"
  "internal/domain/readreceipt/read_receipt.go"
  "pkg/pythonexec/executor.go"
  "pkg/pythonexec/executor_test.go"
  "tests/message_service_test.go"
  "tests/gateway_contract_test.go"
  "tests/websocket_gateway_test.go"
  "tests/read_receipts_test.go"
  "tests/no_shell_execution_test.go"
  "web/package.json"
  "web/index.html"
  "web/src/App.tsx"
  "web/src/App.test.tsx"
  "web/src/api/user.test.ts"
  "web/src/api/user.ts"
  "web/src/components/ui/ActionRow.tsx"
  "web/src/components/ui/Avatar.tsx"
  "web/src/components/ui/Badge.tsx"
  "web/src/components/ui/Button.tsx"
  "web/src/components/ui/Card.tsx"
  "web/src/components/ui/ListCard.tsx"
  "web/src/components/ui/ListItem.tsx"
  "web/src/components/ui/MessageBubble.tsx"
  "web/src/components/ui/NavigationBar.tsx"
  "web/src/components/ui/SearchBox.tsx"
  "web/src/components/ui/TabBar.tsx"
  "web/src/components/ui/TextField.tsx"
  "web/src/components/ui/TopBar.tsx"
  "web/src/components/ui/TopAppBar.tsx"
  "web/src/main.tsx"
  "web/src/components/ContactsPage.tsx"
  "web/src/pages/DiscoverPage.tsx"
  "web/src/pages/MePage.tsx"
  "web/src/features/messages/MessagesPage.tsx"
  "web/src/styles/tokens.css"
  "web/src/styles.css"
  "web/src/vite-env.d.ts"
  "internal/repository/message_storage_contract.go"
  "docker-compose.yml"
  ".env.example"
  "db/migrations/001_init_postgres.sql"
  "scripts/migrate-postgres.sh"
  "scripts/verify-postgres-local.sh"
  "scripts/dev-up.sh"
  "scripts/dev-demo-data.sh"
  "tests/postgres_persistence_integration_test.go"
  "db/migrations/003_agent_conversation_hosting.sql"
  "internal/agentim/hosting.go"
  "internal/agentim/hosting_test.go"
  "internal/agentim/llm_observability.go"
  "internal/agentim/llm_observability_test.go"
  "internal/repository/agent_hosting_repository.go"
  "internal/repository/agent_hosting_memory.go"
  "internal/repository/postgres_agent_hosting.go"
)
require_files "${required_files[@]}"

syntax_check \
  scripts/migrate-postgres.sh \
  scripts/verify-postgres-local.sh \
  scripts/dev-up.sh \
  scripts/dev-demo-data.sh \
  scripts/deploy-k3s.sh \
  scripts/bootstrap-server.sh \
  scripts/test-deploy-k3s.sh \
  scripts/test-no-latest-images.sh \
  scripts/verify-static.sh \
  scripts/verify/lib.sh \
  scripts/verify/verify-security-static.sh \
  scripts/verify/verify-gozero-boundaries.sh \
  scripts/verify/verify-contract-markers.sh \
  scripts/verify/verify-deploy-static.sh \
  scripts/verify/verify-frontend-static.sh

bash "${SCRIPT_DIR}/verify/verify-security-static.sh"
bash "${SCRIPT_DIR}/verify/verify-gozero-boundaries.sh"
bash "${SCRIPT_DIR}/verify/verify-contract-markers.sh"
bash "${SCRIPT_DIR}/verify/verify-deploy-static.sh"
bash "${SCRIPT_DIR}/verify/verify-frontend-static.sh"

echo "static verification passed"
