// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentPrivateConversationsFieldNames          = builder.RawFieldNames(&AgentPrivateConversations{}, true)
	agentPrivateConversationsRows                = strings.Join(agentPrivateConversationsFieldNames, ",")
	agentPrivateConversationsRowsExpectAutoSet   = strings.Join(stringx.Remove(agentPrivateConversationsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentPrivateConversationsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentPrivateConversationsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentPrivateConversationsModel interface {
		Insert(ctx context.Context, data *AgentPrivateConversations) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AgentPrivateConversations, error)
		FindOneByConversationId(ctx context.Context, conversationId string) (*AgentPrivateConversations, error)
		Update(ctx context.Context, data *AgentPrivateConversations) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAgentPrivateConversationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AgentPrivateConversations struct {
		Id              int64        `db:"id"`
		ConversationId  string       `db:"conversation_id"`
		AgentAccountId  string       `db:"agent_account_id"`
		PeerAccountId   string       `db:"peer_account_id"`
		Rounds          string       `db:"rounds"`
		Pending         string       `db:"pending"`
		LastConsumedSeq int64        `db:"last_consumed_seq"`
		State           string       `db:"state"`
		RunningUntil    sql.NullTime `db:"running_until"`
		Version         int64        `db:"version"`
		CreatedAt       time.Time    `db:"created_at"`
		UpdatedAt       time.Time    `db:"updated_at"`
	}
)

func newAgentPrivateConversationsModel(conn sqlx.SqlConn) *defaultAgentPrivateConversationsModel {
	return &defaultAgentPrivateConversationsModel{
		conn:  conn,
		table: `"public"."agent_private_conversations"`,
	}
}

func (m *defaultAgentPrivateConversationsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAgentPrivateConversationsModel) FindOne(ctx context.Context, id int64) (*AgentPrivateConversations, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", agentPrivateConversationsRows, m.table)
	var resp AgentPrivateConversations
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentPrivateConversationsModel) FindOneByConversationId(ctx context.Context, conversationId string) (*AgentPrivateConversations, error) {
	var resp AgentPrivateConversations
	query := fmt.Sprintf("select %s from %s where conversation_id = $1 limit 1", agentPrivateConversationsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, conversationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentPrivateConversationsModel) Insert(ctx context.Context, data *AgentPrivateConversations) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, agentPrivateConversationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.AgentAccountId, data.PeerAccountId, data.Rounds, data.Pending, data.LastConsumedSeq, data.State, data.RunningUntil, data.Version)
	return ret, err
}

func (m *defaultAgentPrivateConversationsModel) Update(ctx context.Context, newData *AgentPrivateConversations) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, agentPrivateConversationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ConversationId, newData.AgentAccountId, newData.PeerAccountId, newData.Rounds, newData.Pending, newData.LastConsumedSeq, newData.State, newData.RunningUntil, newData.Version)
	return err
}

func (m *defaultAgentPrivateConversationsModel) tableName() string {
	return m.table
}
