// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentTriggerIdempotencyFieldNames          = builder.RawFieldNames(&AgentTriggerIdempotency{}, true)
	agentTriggerIdempotencyRows                = strings.Join(agentTriggerIdempotencyFieldNames, ",")
	agentTriggerIdempotencyRowsExpectAutoSet   = strings.Join(stringx.Remove(agentTriggerIdempotencyFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentTriggerIdempotencyRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentTriggerIdempotencyFieldNames, "idempotency_key", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentTriggerIdempotencyModel interface {
		Insert(ctx context.Context, data *AgentTriggerIdempotency) (sql.Result, error)
		FindOne(ctx context.Context, idempotencyKey string) (*AgentTriggerIdempotency, error)
		Update(ctx context.Context, data *AgentTriggerIdempotency) error
		Delete(ctx context.Context, idempotencyKey string) error
	}

	defaultAgentTriggerIdempotencyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AgentTriggerIdempotency struct {
		IdempotencyKey      string    `db:"idempotency_key"`
		ConversationId      string    `db:"conversation_id"`
		AgentAccountId      string    `db:"agent_account_id"`
		TriggerServerMsgId  string    `db:"trigger_server_msg_id"`
		TriggerEventId      string    `db:"trigger_event_id"`
		Status              string    `db:"status"`
		ResponseServerMsgId string    `db:"response_server_msg_id"`
		ErrorMessage        string    `db:"error_message"`
		CreatedAt           time.Time `db:"created_at"`
		UpdatedAt           time.Time `db:"updated_at"`
	}
)

func newAgentTriggerIdempotencyModel(conn sqlx.SqlConn) *defaultAgentTriggerIdempotencyModel {
	return &defaultAgentTriggerIdempotencyModel{
		conn:  conn,
		table: `"public"."agent_trigger_idempotency"`,
	}
}

func (m *defaultAgentTriggerIdempotencyModel) Delete(ctx context.Context, idempotencyKey string) error {
	query := fmt.Sprintf("delete from %s where idempotency_key = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, idempotencyKey)
	return err
}

func (m *defaultAgentTriggerIdempotencyModel) FindOne(ctx context.Context, idempotencyKey string) (*AgentTriggerIdempotency, error) {
	query := fmt.Sprintf("select %s from %s where idempotency_key = $1 limit 1", agentTriggerIdempotencyRows, m.table)
	var resp AgentTriggerIdempotency
	err := m.conn.QueryRowCtx(ctx, &resp, query, idempotencyKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentTriggerIdempotencyModel) Insert(ctx context.Context, data *AgentTriggerIdempotency) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, agentTriggerIdempotencyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.IdempotencyKey, data.ConversationId, data.AgentAccountId, data.TriggerServerMsgId, data.TriggerEventId, data.Status, data.ResponseServerMsgId, data.ErrorMessage)
	return ret, err
}

func (m *defaultAgentTriggerIdempotencyModel) Update(ctx context.Context, data *AgentTriggerIdempotency) error {
	query := fmt.Sprintf("update %s set %s where idempotency_key = $1", m.table, agentTriggerIdempotencyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.IdempotencyKey, data.ConversationId, data.AgentAccountId, data.TriggerServerMsgId, data.TriggerEventId, data.Status, data.ResponseServerMsgId, data.ErrorMessage)
	return err
}

func (m *defaultAgentTriggerIdempotencyModel) tableName() string {
	return m.table
}
