// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentConversationHostingFieldNames          = builder.RawFieldNames(&AgentConversationHosting{}, true)
	agentConversationHostingRows                = strings.Join(agentConversationHostingFieldNames, ",")
	agentConversationHostingRowsExpectAutoSet   = strings.Join(stringx.Remove(agentConversationHostingFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentConversationHostingRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentConversationHostingFieldNames, "conversation_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentConversationHostingModel interface {
		Insert(ctx context.Context, data *AgentConversationHosting) (sql.Result, error)
		FindOne(ctx context.Context, conversationId string) (*AgentConversationHosting, error)
		Update(ctx context.Context, data *AgentConversationHosting) error
		Delete(ctx context.Context, conversationId string) error
	}

	defaultAgentConversationHostingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AgentConversationHosting struct {
		ConversationId             string    `db:"conversation_id"`
		AgentAccountId             string    `db:"agent_account_id"`
		Enabled                    bool      `db:"enabled"`
		AllowAgentMessageRecursion bool      `db:"allow_agent_message_recursion"`
		CreatedAt                  time.Time `db:"created_at"`
		UpdatedAt                  time.Time `db:"updated_at"`
	}
)

func newAgentConversationHostingModel(conn sqlx.SqlConn) *defaultAgentConversationHostingModel {
	return &defaultAgentConversationHostingModel{
		conn:  conn,
		table: `"public"."agent_conversation_hosting"`,
	}
}

func (m *defaultAgentConversationHostingModel) Delete(ctx context.Context, conversationId string) error {
	query := fmt.Sprintf("delete from %s where conversation_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, conversationId)
	return err
}

func (m *defaultAgentConversationHostingModel) FindOne(ctx context.Context, conversationId string) (*AgentConversationHosting, error) {
	query := fmt.Sprintf("select %s from %s where conversation_id = $1 limit 1", agentConversationHostingRows, m.table)
	var resp AgentConversationHosting
	err := m.conn.QueryRowCtx(ctx, &resp, query, conversationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentConversationHostingModel) Insert(ctx context.Context, data *AgentConversationHosting) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, agentConversationHostingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.AgentAccountId, data.Enabled, data.AllowAgentMessageRecursion)
	return ret, err
}

func (m *defaultAgentConversationHostingModel) Update(ctx context.Context, data *AgentConversationHosting) error {
	query := fmt.Sprintf("update %s set %s where conversation_id = $1", m.table, agentConversationHostingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.AgentAccountId, data.Enabled, data.AllowAgentMessageRecursion)
	return err
}

func (m *defaultAgentConversationHostingModel) tableName() string {
	return m.table
}
