// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentsFieldNames          = builder.RawFieldNames(&Agents{}, true)
	agentsRows                = strings.Join(agentsFieldNames, ",")
	agentsRowsExpectAutoSet   = strings.Join(stringx.Remove(agentsFieldNames, "agent_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentsFieldNames, "agent_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentsModel interface {
		Insert(ctx context.Context, data *Agents) (sql.Result, error)
		FindOne(ctx context.Context, agentId int64) (*Agents, error)
		FindOneByAccountId(ctx context.Context, accountId string) (*Agents, error)
		Update(ctx context.Context, data *Agents) error
		Delete(ctx context.Context, agentId int64) error
	}

	defaultAgentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Agents struct {
		AgentId     int64     `db:"agent_id"`
		AccountId   string    `db:"account_id"`
		Name        string    `db:"name"`
		Description string    `db:"description"`
		Status      string    `db:"status"`
		CreatedBy   string    `db:"created_by"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newAgentsModel(conn sqlx.SqlConn) *defaultAgentsModel {
	return &defaultAgentsModel{
		conn:  conn,
		table: `"public"."agents"`,
	}
}

func (m *defaultAgentsModel) Delete(ctx context.Context, agentId int64) error {
	query := fmt.Sprintf("delete from %s where agent_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, agentId)
	return err
}

func (m *defaultAgentsModel) FindOne(ctx context.Context, agentId int64) (*Agents, error) {
	query := fmt.Sprintf("select %s from %s where agent_id = $1 limit 1", agentsRows, m.table)
	var resp Agents
	err := m.conn.QueryRowCtx(ctx, &resp, query, agentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentsModel) FindOneByAccountId(ctx context.Context, accountId string) (*Agents, error) {
	var resp Agents
	query := fmt.Sprintf("select %s from %s where account_id = $1 limit 1", agentsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, accountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentsModel) Insert(ctx context.Context, data *Agents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, agentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.Name, data.Description, data.Status, data.CreatedBy)
	return ret, err
}

func (m *defaultAgentsModel) Update(ctx context.Context, newData *Agents) error {
	query := fmt.Sprintf("update %s set %s where agent_id = $1", m.table, agentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AgentId, newData.AccountId, newData.Name, newData.Description, newData.Status, newData.CreatedBy)
	return err
}

func (m *defaultAgentsModel) tableName() string {
	return m.table
}
