// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentToolsFieldNames          = builder.RawFieldNames(&AgentTools{}, true)
	agentToolsRows                = strings.Join(agentToolsFieldNames, ",")
	agentToolsRowsExpectAutoSet   = strings.Join(stringx.Remove(agentToolsFieldNames, "tool_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentToolsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentToolsFieldNames, "tool_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentToolsModel interface {
		Insert(ctx context.Context, data *AgentTools) (sql.Result, error)
		FindOne(ctx context.Context, toolId int64) (*AgentTools, error)
		FindOneByName(ctx context.Context, name string) (*AgentTools, error)
		Update(ctx context.Context, data *AgentTools) error
		Delete(ctx context.Context, toolId int64) error
	}

	defaultAgentToolsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AgentTools struct {
		ToolId           int64         `db:"tool_id"`
		Name             string        `db:"name"`
		Description      string        `db:"description"`
		ToolType         string        `db:"tool_type"`
		McpServerId      sql.NullInt64 `db:"mcp_server_id"`
		McpToolName      string        `db:"mcp_tool_name"`
		LocalHandlerKey  string        `db:"local_handler_key"`
		BuiltinKey       string        `db:"builtin_key"`
		InputSchemaJson  string        `db:"input_schema_json"`
		OutputSchemaJson string        `db:"output_schema_json"`
		PermissionLevel  string        `db:"permission_level"`
		Status           string        `db:"status"`
		AdminConfigured  bool          `db:"admin_configured"`
		CreatedBy        string        `db:"created_by"`
		CreatedAt        time.Time     `db:"created_at"`
		UpdatedAt        time.Time     `db:"updated_at"`
	}
)

func newAgentToolsModel(conn sqlx.SqlConn) *defaultAgentToolsModel {
	return &defaultAgentToolsModel{
		conn:  conn,
		table: `"public"."agent_tools"`,
	}
}

func (m *defaultAgentToolsModel) Delete(ctx context.Context, toolId int64) error {
	query := fmt.Sprintf("delete from %s where tool_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, toolId)
	return err
}

func (m *defaultAgentToolsModel) FindOne(ctx context.Context, toolId int64) (*AgentTools, error) {
	query := fmt.Sprintf("select %s from %s where tool_id = $1 limit 1", agentToolsRows, m.table)
	var resp AgentTools
	err := m.conn.QueryRowCtx(ctx, &resp, query, toolId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentToolsModel) FindOneByName(ctx context.Context, name string) (*AgentTools, error) {
	var resp AgentTools
	query := fmt.Sprintf("select %s from %s where name = $1 limit 1", agentToolsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentToolsModel) Insert(ctx context.Context, data *AgentTools) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)", m.table, agentToolsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.ToolType, data.McpServerId, data.McpToolName, data.LocalHandlerKey, data.BuiltinKey, data.InputSchemaJson, data.OutputSchemaJson, data.PermissionLevel, data.Status, data.AdminConfigured, data.CreatedBy)
	return ret, err
}

func (m *defaultAgentToolsModel) Update(ctx context.Context, newData *AgentTools) error {
	query := fmt.Sprintf("update %s set %s where tool_id = $1", m.table, agentToolsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ToolId, newData.Name, newData.Description, newData.ToolType, newData.McpServerId, newData.McpToolName, newData.LocalHandlerKey, newData.BuiltinKey, newData.InputSchemaJson, newData.OutputSchemaJson, newData.PermissionLevel, newData.Status, newData.AdminConfigured, newData.CreatedBy)
	return err
}

func (m *defaultAgentToolsModel) tableName() string {
	return m.table
}
