// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	conversationAiHostingSettingsFieldNames          = builder.RawFieldNames(&ConversationAiHostingSettings{}, true)
	conversationAiHostingSettingsRows                = strings.Join(conversationAiHostingSettingsFieldNames, ",")
	conversationAiHostingSettingsRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationAiHostingSettingsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	conversationAiHostingSettingsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(conversationAiHostingSettingsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	conversationAiHostingSettingsModel interface {
		Insert(ctx context.Context, data *ConversationAiHostingSettings) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ConversationAiHostingSettings, error)
		FindOneByConversationId(ctx context.Context, conversationId string) (*ConversationAiHostingSettings, error)
		FindOneByOwnerAccountIdConversationId(ctx context.Context, ownerAccountId string, conversationId string) (*ConversationAiHostingSettings, error)
		Update(ctx context.Context, data *ConversationAiHostingSettings) error
		Delete(ctx context.Context, id int64) error
	}

	defaultConversationAiHostingSettingsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ConversationAiHostingSettings struct {
		OwnerAccountId    string    `db:"owner_account_id"`
		ConversationId    string    `db:"conversation_id"`
		Enabled           bool      `db:"enabled"`
		Mode              string    `db:"mode"`
		MaxRecentMessages int64     `db:"max_recent_messages"`
		SummaryEnabled    bool      `db:"summary_enabled"`
		CreatedAt         time.Time `db:"created_at"`
		UpdatedAt         time.Time `db:"updated_at"`
		Id                int64     `db:"id"`
	}
)

func newConversationAiHostingSettingsModel(conn sqlx.SqlConn) *defaultConversationAiHostingSettingsModel {
	return &defaultConversationAiHostingSettingsModel{
		conn:  conn,
		table: `"public"."conversation_ai_hosting_settings"`,
	}
}

func (m *defaultConversationAiHostingSettingsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConversationAiHostingSettingsModel) FindOne(ctx context.Context, id int64) (*ConversationAiHostingSettings, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", conversationAiHostingSettingsRows, m.table)
	var resp ConversationAiHostingSettings
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationAiHostingSettingsModel) FindOneByConversationId(ctx context.Context, conversationId string) (*ConversationAiHostingSettings, error) {
	var resp ConversationAiHostingSettings
	query := fmt.Sprintf("select %s from %s where conversation_id = $1 limit 1", conversationAiHostingSettingsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, conversationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationAiHostingSettingsModel) FindOneByOwnerAccountIdConversationId(ctx context.Context, ownerAccountId string, conversationId string) (*ConversationAiHostingSettings, error) {
	var resp ConversationAiHostingSettings
	query := fmt.Sprintf("select %s from %s where owner_account_id = $1 and conversation_id = $2 limit 1", conversationAiHostingSettingsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, ownerAccountId, conversationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationAiHostingSettingsModel) Insert(ctx context.Context, data *ConversationAiHostingSettings) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, conversationAiHostingSettingsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OwnerAccountId, data.ConversationId, data.Enabled, data.Mode, data.MaxRecentMessages, data.SummaryEnabled)
	return ret, err
}

func (m *defaultConversationAiHostingSettingsModel) Update(ctx context.Context, newData *ConversationAiHostingSettings) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, conversationAiHostingSettingsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.OwnerAccountId, newData.ConversationId, newData.Enabled, newData.Mode, newData.MaxRecentMessages, newData.SummaryEnabled)
	return err
}

func (m *defaultConversationAiHostingSettingsModel) tableName() string {
	return m.table
}
