// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ConversationAIHostingData struct {
	ConversationID    string `json:"conversationId"`
	ChatType          string `json:"chatType"`
	Enabled           bool   `json:"enabled"`
	Available         bool   `json:"available"`
	PeerEnabled       bool   `json:"peerEnabled"`
	UnavailableReason string `json:"unavailableReason,optional"`
	MaxRecentMessages int64  `json:"maxRecentMessages"`
	SummaryEnabled    bool   `json:"summaryEnabled"`
}

type ConversationAIHostingReq struct {
	ConversationID string `path:"conversation_id"`
}

type ConversationAIHostingResp struct {
	Code    string                    `json:"code"`
	Message string                    `json:"message"`
	Data    ConversationAIHostingData `json:"data"`
}

type ConversationSeqState struct {
	ConversationID string   `json:"conversationId"`
	MaxSeq         int64    `json:"maxSeq"`
	HasReadSeq     int64    `json:"hasReadSeq"`
	UnreadCount    int64    `json:"unreadCount"`
	MaxSeqTime     int64    `json:"maxSeqTime"`
	LastMessage    *Message `json:"lastMessage,omitempty"`
}

type ConversationSeqsData struct {
	States []ConversationSeqState `json:"states"`
}

type ConversationSeqsReq struct {
	ConversationIDs string `form:"conversationIds,optional"`
}

type ConversationSeqsResp struct {
	Code    string               `json:"code"`
	Message string               `json:"message"`
	Data    ConversationSeqsData `json:"data"`
}

type CreateFeedbackReq struct {
	Category   string                 `json:"category"`
	Title      string                 `json:"title"`
	Content    string                 `json:"content"`
	Contact    string                 `json:"contact,optional"`
	PageURL    string                 `json:"pageUrl,optional"`
	UserAgent  string                 `json:"userAgent,optional"`
	ClientMeta map[string]interface{} `json:"clientMeta,optional"`
}

type CreateFeedbackResp struct {
	Code    string       `json:"code"`
	Message string       `json:"message"`
	Data    FeedbackData `json:"data"`
}

type FeedbackData struct {
	FeedbackID string `json:"feedbackId"`
	Status     string `json:"status"`
}

type MarkConversationAsReadData struct {
	ConversationID string `json:"conversationId"`
	HasReadSeq     int64  `json:"hasReadSeq"`
	MaxSeq         int64  `json:"maxSeq"`
	UnreadCount    int64  `json:"unreadCount"`
	Updated        bool   `json:"updated"`
}

type MarkConversationAsReadReq struct {
	ConversationID string `path:"conversation_id"`
	HasReadSeq     int64  `json:"hasReadSeq"`
}

type MarkConversationAsReadResp struct {
	Code    string                     `json:"code"`
	Message string                     `json:"message"`
	Data    MarkConversationAsReadData `json:"data"`
}

type Message struct {
	ServerMsgID           string `json:"serverMsgId"`
	ClientMsgID           string `json:"clientMsgId"`
	ConversationID        string `json:"conversationId"`
	Seq                   int64  `json:"seq"`
	SenderID              string `json:"senderId"`
	ReceiverID            string `json:"receiverId"`
	GroupID               string `json:"groupId"`
	ChatType              string `json:"chatType"`
	ContentType           string `json:"contentType"`
	Content               string `json:"content"`
	MessageOrigin         string `json:"messageOrigin"`
	AgentAccountID        string `json:"agentAccountId,optional"`
	TriggerServerMsgID    string `json:"triggerServerMsgId,optional"`
	AgentRunID            string `json:"agentRunId,optional"`
	AllowRecursiveTrigger bool   `json:"allowRecursiveTrigger,optional"`
	SendTime              int64  `json:"sendTime"`
	CreatedAt             int64  `json:"createdAt"`
}

type PullMessagesData struct {
	Messages []Message `json:"messages"`
	IsEnd    bool      `json:"isEnd"`
	NextSeq  int64     `json:"nextSeq"`
}

type PullMessagesReq struct {
	ConversationID string `path:"conversation_id"`
	FromSeq        int64  `form:"fromSeq,optional"`
	ToSeq          int64  `form:"toSeq,optional"`
	Limit          int64  `form:"limit,optional"`
	Order          string `form:"order,optional"`
}

type PullMessagesResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    PullMessagesData `json:"data"`
}

type SendMessageData struct {
	Message      Message `json:"message"`
	Deduplicated bool    `json:"deduplicated"`
}

type SendMessageReq struct {
	SenderID              string `json:"senderId,optional"`
	ReceiverID            string `json:"receiverId,optional"`
	GroupID               string `json:"groupId,optional"`
	ChatType              string `json:"chatType"`
	ClientMsgID           string `json:"clientMsgId"`
	ContentType           string `json:"contentType"`
	Content               string `json:"content"`
	MessageOrigin         string `json:"messageOrigin,optional"`
	AgentAccountID        string `json:"agentAccountId,optional"`
	TriggerServerMsgID    string `json:"triggerServerMsgId,optional"`
	AgentRunID            string `json:"agentRunId,optional"`
	AllowRecursiveTrigger bool   `json:"allowRecursiveTrigger,optional"`
}

type SendMessageResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    SendMessageData `json:"data"`
}

type UpdateConversationAIHostingReq struct {
	ConversationID string `path:"conversation_id"`
	Enabled        bool   `json:"enabled"`
}
