// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/internal/rpcgen/auth/internal/logic"
	"github.com/wujunhui99/agents_im/internal/rpcgen/auth/internal/svc"
	"github.com/wujunhui99/agents_im/proto/authpb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	authpb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Register(ctx context.Context, in *authpb.RegisterRequest) (*authpb.AuthResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServiceServer) Login(ctx context.Context, in *authpb.LoginRequest) (*authpb.AuthResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServiceServer) ValidateToken(ctx context.Context, in *authpb.ValidateTokenRequest) (*authpb.ValidateTokenResponse, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *AuthServiceServer) ParseToken(ctx context.Context, in *authpb.ValidateTokenRequest) (*authpb.ValidateTokenResponse, error) {
	l := logic.NewParseTokenLogic(ctx, s.svcCtx)
	return l.ParseToken(in)
}
