// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: service/agent/rpc/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_GetConversationAIHosting_FullMethodName    = "/agent.v1.Agent/GetConversationAIHosting"
	Agent_UpdateConversationAIHosting_FullMethodName = "/agent.v1.Agent/UpdateConversationAIHosting"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent 是 agent 域 RPC（04-agent §3.2，#340）。agent-rpc 同时是 agent.trigger.v1
// 的消费者 worker（见 agent.go），gRPC 面当前只暴露 AI 托管开关 CRUD ——
// 数据 owner = agent 域（#463 临时塞进 msg.proto 的两个 RPC 随本 issue 迁出）。
type AgentClient interface {
	// AI 托管开关：普通用户在双人单聊里开关「由 AI 代我回复」。
	GetConversationAIHosting(ctx context.Context, in *GetConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error)
	UpdateConversationAIHosting(ctx context.Context, in *UpdateConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) GetConversationAIHosting(ctx context.Context, in *GetConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationAIHostingState)
	err := c.cc.Invoke(ctx, Agent_GetConversationAIHosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpdateConversationAIHosting(ctx context.Context, in *UpdateConversationAIHostingRequest, opts ...grpc.CallOption) (*ConversationAIHostingState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationAIHostingState)
	err := c.cc.Invoke(ctx, Agent_UpdateConversationAIHosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent 是 agent 域 RPC（04-agent §3.2，#340）。agent-rpc 同时是 agent.trigger.v1
// 的消费者 worker（见 agent.go），gRPC 面当前只暴露 AI 托管开关 CRUD ——
// 数据 owner = agent 域（#463 临时塞进 msg.proto 的两个 RPC 随本 issue 迁出）。
type AgentServer interface {
	// AI 托管开关：普通用户在双人单聊里开关「由 AI 代我回复」。
	GetConversationAIHosting(context.Context, *GetConversationAIHostingRequest) (*ConversationAIHostingState, error)
	UpdateConversationAIHosting(context.Context, *UpdateConversationAIHostingRequest) (*ConversationAIHostingState, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) GetConversationAIHosting(context.Context, *GetConversationAIHostingRequest) (*ConversationAIHostingState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversationAIHosting not implemented")
}
func (UnimplementedAgentServer) UpdateConversationAIHosting(context.Context, *UpdateConversationAIHostingRequest) (*ConversationAIHostingState, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConversationAIHosting not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_GetConversationAIHosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationAIHostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetConversationAIHosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetConversationAIHosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetConversationAIHosting(ctx, req.(*GetConversationAIHostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpdateConversationAIHosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationAIHostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpdateConversationAIHosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_UpdateConversationAIHosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpdateConversationAIHosting(ctx, req.(*UpdateConversationAIHostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversationAIHosting",
			Handler:    _Agent_GetConversationAIHosting_Handler,
		},
		{
			MethodName: "UpdateConversationAIHosting",
			Handler:    _Agent_UpdateConversationAIHosting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/agent/rpc/agent.proto",
}
