// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/mail.proto

package mailpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTemplateEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recipients     []string               `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	TemplateId     uint64                 `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData   map[string]string      `protobuf:"bytes,3,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Subject        string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	FromEmail      string                 `protobuf:"bytes,5,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	FromName       string                 `protobuf:"bytes,6,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendTemplateEmailRequest) Reset() {
	*x = SendTemplateEmailRequest{}
	mi := &file_proto_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplateEmailRequest) ProtoMessage() {}

func (x *SendTemplateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplateEmailRequest.ProtoReflect.Descriptor instead.
func (*SendTemplateEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *SendTemplateEmailRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendTemplateEmailRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SendTemplateEmailRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendTemplateEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendTemplateEmailRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *SendTemplateEmailRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendTemplateEmailRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SendTemplateEmailResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Provider          string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRequestId string                 `protobuf:"bytes,2,opt,name=provider_request_id,json=providerRequestId,proto3" json:"provider_request_id,omitempty"`
	ProviderMessageId string                 `protobuf:"bytes,3,opt,name=provider_message_id,json=providerMessageId,proto3" json:"provider_message_id,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendTemplateEmailResponse) Reset() {
	*x = SendTemplateEmailResponse{}
	mi := &file_proto_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplateEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplateEmailResponse) ProtoMessage() {}

func (x *SendTemplateEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplateEmailResponse.ProtoReflect.Descriptor instead.
func (*SendTemplateEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendTemplateEmailResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SendTemplateEmailResponse) GetProviderRequestId() string {
	if x != nil {
		return x.ProviderRequestId
	}
	return ""
}

func (x *SendTemplateEmailResponse) GetProviderMessageId() string {
	if x != nil {
		return x.ProviderMessageId
	}
	return ""
}

func (x *SendTemplateEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendTemplateEmailResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SendTemplateEmailResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_mail_proto protoreflect.FileDescriptor

const file_proto_mail_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mail.proto\x12\amail.v1\"\xf5\x02\n" +
	"\x18SendTemplateEmailRequest\x12\x1e\n" +
	"\n" +
	"recipients\x18\x01 \x03(\tR\n" +
	"recipients\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x04R\n" +
	"templateId\x12X\n" +
	"\rtemplate_data\x18\x03 \x03(\v23.mail.v1.SendTemplateEmailRequest.TemplateDataEntryR\ftemplateData\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"from_email\x18\x05 \x01(\tR\tfromEmail\x12\x1b\n" +
	"\tfrom_name\x18\x06 \x01(\tR\bfromName\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x19SendTemplateEmailResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12.\n" +
	"\x13provider_request_id\x18\x02 \x01(\tR\x11providerRequestId\x12.\n" +
	"\x13provider_message_id\x18\x03 \x01(\tR\x11providerMessageId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage2i\n" +
	"\vMailService\x12Z\n" +
	"\x11SendTemplateEmail\x12!.mail.v1.SendTemplateEmailRequest\x1a\".mail.v1.SendTemplateEmailResponseB.Z,github.com/wujunhui99/agents_im/proto/mailpbb\x06proto3"

var (
	file_proto_mail_proto_rawDescOnce sync.Once
	file_proto_mail_proto_rawDescData []byte
)

func file_proto_mail_proto_rawDescGZIP() []byte {
	file_proto_mail_proto_rawDescOnce.Do(func() {
		file_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)))
	})
	return file_proto_mail_proto_rawDescData
}

var file_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_mail_proto_goTypes = []any{
	(*SendTemplateEmailRequest)(nil),  // 0: mail.v1.SendTemplateEmailRequest
	(*SendTemplateEmailResponse)(nil), // 1: mail.v1.SendTemplateEmailResponse
	nil,                               // 2: mail.v1.SendTemplateEmailRequest.TemplateDataEntry
}
var file_proto_mail_proto_depIdxs = []int32{
	2, // 0: mail.v1.SendTemplateEmailRequest.template_data:type_name -> mail.v1.SendTemplateEmailRequest.TemplateDataEntry
	0, // 1: mail.v1.MailService.SendTemplateEmail:input_type -> mail.v1.SendTemplateEmailRequest
	1, // 2: mail.v1.MailService.SendTemplateEmail:output_type -> mail.v1.SendTemplateEmailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mail_proto_init() }
func file_proto_mail_proto_init() {
	if File_proto_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_proto_depIdxs,
		MessageInfos:      file_proto_mail_proto_msgTypes,
	}.Build()
	File_proto_mail_proto = out.File
	file_proto_mail_proto_goTypes = nil
	file_proto_mail_proto_depIdxs = nil
}
