// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	friends "github.com/wujunhui99/agents_im/service/friends/api/internal/handler/friends"
	"github.com/wujunhui99/agents_im/service/friends/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.DeviceAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/friends",
					Handler: friends.AddFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friends",
					Handler: friends.ListFriendsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/friends/:user_id",
					Handler: friends.DeleteFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friends/:user_id",
					Handler: friends.GetFriendshipHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friends/requests",
					Handler: friends.ListFriendRequestsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friends/requests/:user_id/accept",
					Handler: friends.AcceptFriendRequestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friends/requests/:user_id/reject",
					Handler: friends.RejectFriendRequestHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
