// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admin "github.com/wujunhui99/agents_im/service/admin/api/internal/handler/admin"
	"github.com/wujunhui99/agents_im/service/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.DeviceAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/conversations/:conversation_id/messages",
					Handler: admin.GetConversationMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/conversations/:conversation_id/messages/:server_msg_id/replay-agent",
					Handler: admin.ReplayAgentMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/dashboard",
					Handler: admin.DashboardHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/llm-traces",
					Handler: admin.ListLLMTracesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/llm-traces/:trace_id",
					Handler: admin.GetLLMTraceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/test-accounts",
					Handler: admin.CreateTestAccountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users",
					Handler: admin.SearchUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:account_id",
					Handler: admin.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:account_id/conversations",
					Handler: admin.GetUserConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:account_id/friends",
					Handler: admin.GetUserFriendsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/feedback",
					Handler: admin.ListFeedbackHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/feedback/:feedback_id",
					Handler: admin.GetFeedbackHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/admin/feedback/:feedback_id",
					Handler: admin.UpdateFeedbackHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/admin/task-reports",
					Handler: admin.ListTaskReportsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/admin/task-reports",
					Handler: admin.IngestTaskReportHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
