// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/service/message/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/message/rpc/internal/svc"
	messagepb "github.com/wujunhui99/agents_im/service/message/rpc/message"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	messagepb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) SendMessage(ctx context.Context, in *messagepb.SendMessageRequest) (*messagepb.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *MessageServiceServer) PullMessages(ctx context.Context, in *messagepb.PullMessagesRequest) (*messagepb.PullMessagesResponse, error) {
	l := logic.NewPullMessagesLogic(ctx, s.svcCtx)
	return l.PullMessages(in)
}

func (s *MessageServiceServer) GetConversationSeqs(ctx context.Context, in *messagepb.GetConversationSeqsRequest) (*messagepb.GetConversationSeqsResponse, error) {
	l := logic.NewGetConversationSeqsLogic(ctx, s.svcCtx)
	return l.GetConversationSeqs(in)
}

func (s *MessageServiceServer) MarkConversationAsRead(ctx context.Context, in *messagepb.MarkConversationAsReadRequest) (*messagepb.MarkConversationAsReadResponse, error) {
	l := logic.NewMarkConversationAsReadLogic(ctx, s.svcCtx)
	return l.MarkConversationAsRead(in)
}
