// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/service/auth/rpc/auth"
	"github.com/wujunhui99/agents_im/service/auth/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/auth/rpc/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) RequestRegistrationEmailCode(ctx context.Context, in *auth.RegistrationEmailCodeRequest) (*auth.RegistrationEmailCodeResponse, error) {
	l := logic.NewRequestRegistrationEmailCodeLogic(ctx, s.svcCtx)
	return l.RequestRegistrationEmailCode(in)
}

func (s *AuthServer) Register(ctx context.Context, in *auth.RegisterRequest) (*auth.AuthResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServer) Login(ctx context.Context, in *auth.LoginRequest) (*auth.AuthResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServer) ValidateToken(ctx context.Context, in *auth.ValidateTokenRequest) (*auth.ValidateTokenResponse, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *AuthServer) ParseToken(ctx context.Context, in *auth.ValidateTokenRequest) (*auth.ValidateTokenResponse, error) {
	l := logic.NewParseTokenLogic(ctx, s.svcCtx)
	return l.ParseToken(in)
}

// EnsureTestCredential 为测试账户（account_type=test）创建/重置登录凭据。
func (s *AuthServer) EnsureTestCredential(ctx context.Context, in *auth.EnsureTestCredentialRequest) (*auth.EnsureTestCredentialResponse, error) {
	l := logic.NewEnsureTestCredentialLogic(ctx, s.svcCtx)
	return l.EnsureTestCredential(in)
}

// EnsureAdminCredential 为管理员账号补齐首次登录凭据。
func (s *AuthServer) EnsureAdminCredential(ctx context.Context, in *auth.EnsureAdminCredentialRequest) (*auth.EnsureAdminCredentialResponse, error) {
	l := logic.NewEnsureAdminCredentialLogic(ctx, s.svcCtx)
	return l.EnsureAdminCredential(in)
}
