// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: friends.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/internal/rpcgen/friends/internal/logic"
	"github.com/wujunhui99/agents_im/internal/rpcgen/friends/internal/svc"
	"github.com/wujunhui99/agents_im/proto/friendspb"
)

type FriendsServiceServer struct {
	svcCtx *svc.ServiceContext
	friendspb.UnimplementedFriendsServiceServer
}

func NewFriendsServiceServer(svcCtx *svc.ServiceContext) *FriendsServiceServer {
	return &FriendsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendsServiceServer) AddFriend(ctx context.Context, in *friendspb.AddFriendRequest) (*friendspb.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *FriendsServiceServer) DeleteFriend(ctx context.Context, in *friendspb.DeleteFriendRequest) (*friendspb.DeleteFriendResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *FriendsServiceServer) ListFriends(ctx context.Context, in *friendspb.ListFriendsRequest) (*friendspb.ListFriendsResponse, error) {
	l := logic.NewListFriendsLogic(ctx, s.svcCtx)
	return l.ListFriends(in)
}

func (s *FriendsServiceServer) GetFriendship(ctx context.Context, in *friendspb.GetFriendshipRequest) (*friendspb.GetFriendshipResponse, error) {
	l := logic.NewGetFriendshipLogic(ctx, s.svcCtx)
	return l.GetFriendship(in)
}
