// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: mail.proto

package server

import (
	"context"

	"github.com/wujunhui99/agents_im/service/mail/rpc/internal/logic"
	"github.com/wujunhui99/agents_im/service/mail/rpc/internal/svc"
	mail "github.com/wujunhui99/agents_im/service/mail/rpc/mail"
)

type MailServiceServer struct {
	svcCtx *svc.ServiceContext
	mail.UnimplementedMailServiceServer
}

func NewMailServiceServer(svcCtx *svc.ServiceContext) *MailServiceServer {
	return &MailServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MailServiceServer) SendTemplateEmail(ctx context.Context, in *mail.SendTemplateEmailRequest) (*mail.SendTemplateEmailResponse, error) {
	l := logic.NewSendTemplateEmailLogic(ctx, s.svcCtx)
	return l.SendTemplateEmail(in)
}
